---
deployment:
  tasks:
    - /usr/local/bin/ea-php82 -d error_log=/home2/horizonstr/horizons-membership-update/deployment-php.log scripts/deploy-display-currency.php /home2/horizonstr/public_html/ --publish
    - /usr/local/bin/ea-php82 -d error_log=/home2/horizonstr/horizons-membership-update/deployment-php.log scripts/deploy-travel-kit.php /home2/horizonstr/public_html/ --publish
