import assert from 'node:assert/strict';
import fs from 'node:fs';
import {JSDOM} from 'jsdom';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {install}=require('../src/workbook-experiences/native-experiences.js');
const rows=JSON.parse(fs.readFileSync(new URL('../src/workbook-experiences/native-locales.json',import.meta.url),'utf8'));
const locales=Object.fromEntries(Object.entries(rows.rows).map(([lang,row])=>[lang,Object.fromEntries(rows.keys.map((key,i)=>[key,row.split('|')[i]]))]));
const dom=new JSDOM(`<body><header class="topbar"><nav class="hzn-top-controls"></nav></header><main><div id="hzn-home"></div><select id="locale"><option value="ar">ar</option></select><nav id="stages"></nav><section id="activity"><p class="story-sentence">تُخْرِجُ <span class="target-letter">حَ</span>بْلًا</p><button id="listen" title="إستمع للقصة" aria-label="إِسْتَمِعْ للقصة"><svg><path d="M0 0"></path></svg>إستمع للقصة</button><button id="first-person">أستمع ثم أختار</button><button id="card" class="letter-card" aria-pressed="true">ب</button><div id="shadow"></div></section></main></body>`,{url:'https://horizons.invalid/learn/',pretendToBeVisual:true});
const {window}=dom,doc=window.document;
window.hznFocusShell={currentLearnerKey:()=> 'fixture-learner'};
const story=doc.querySelector('.story-sentence'),card=doc.querySelector('#card'),svg=doc.querySelector('#listen svg');
const initialStory=story.outerHTML;
const root=doc.querySelector('#shadow').attachShadow({mode:'open'});
root.innerHTML='<div class="b4"><div id="reader-inner"><button id="shadow-listen">إستمع</button><svg><path fill="var(--fatha)" d="M0 0h10"></path></svg></div></div>';
let calls=0;doc.querySelector('#listen').onclick=()=>calls++;
const api=install(window,doc,{locales,css:'',shadow:''});
assert.equal(doc.querySelector('#listen').textContent,'استمع للقصة');
assert.equal(doc.querySelector('#listen').getAttribute('aria-label'),'اِسْتَمِعْ للقصة');
assert.equal(root.querySelector('#shadow-listen').textContent,'استمع');
assert.equal(doc.querySelector('#first-person').textContent,'أستمع ثم أختار');
assert.equal(svg,doc.querySelector('#listen svg'));
doc.querySelector('#listen').click();assert.equal(calls,1);
api.setTone('dark');
assert.equal(doc.body.dataset.hznTone,'dark');
assert.equal(root.host.dataset.hznTone,'dark');
assert.equal(story.outerHTML,initialStory);
assert.equal(card,doc.querySelector('#card'));assert.equal(card.getAttribute('aria-pressed'),'true');
assert.equal(root.querySelector('path').getAttribute('fill'),'var(--fatha)');
api.destroy();window.close();
console.log('Activity UI: labels corrected without replacing nodes, icons, glyphs or activity state.');
