<?php
declare(strict_types=1);
require __DIR__.'/../src/activation/MembershipService.php';
require __DIR__.'/../src/commerce/TransferCheckout.php';
require __DIR__.'/../src/commerce/MembershipFulfilment.php';
function verifyTransfer(bool $v):void{if(!$v)throw new RuntimeException('ASSERTION_FAILED');}
function rejectTransfer(callable $f,string $message):void{try{$f();}catch(Throwable $e){if($e->getMessage()!==$message)throw $e;return;}throw new RuntimeException('EXPECTED_'.$message);}
$root=sys_get_temp_dir().'/hzn-transfer-'.bin2hex(random_bytes(8));mkdir($root,0700);mkdir($root.'/public_html',0700);
try{
 $key=random_bytes(32);$pair=sodium_crypto_sign_keypair();file_put_contents($root.'/vault.json',json_encode(['schema'=>1,'product'=>\Horizons\PRODUCT,'signing_private_key'=>base64_encode(sodium_crypto_sign_secretkey($pair)),'content_key'=>base64_encode(random_bytes(32))]));$crypto=new \Horizons\Crypto(['data_key'=>base64_encode($key),'vault_path'=>$root.'/vault.json']);$store=new \Horizons\Store($root.'/activation.sqlite');$bridge=new \Horizons\MembershipBridge($store,$crypto);
 $settings=['charges_enabled'=>true,'price_approved'=>true,'bank_adapter_approved'=>true,'activation_adapter_approved'=>true,'product'=>\Horizons\PRODUCT,'merchant_id'=>'test','terminal_id'=>'manual','accounts'=>['family'=>['plans'=>['annual'=>['amount_minor'=>20000,'currency'=>'USD']]]]];
 $purchases=new \HorizonsCommerce\PurchaseLedger($root.'/orders.sqlite',$root.'/public_html',$settings);$members=new \HorizonsCommerce\MembershipLedger($root.'/members.sqlite',$root.'/public_html',$key);$checkout=new \HorizonsCommerce\TransferCheckout($root.'/billing.sqlite',$root.'/public_html',$purchases,$key,$members);$fulfilment=new \HorizonsCommerce\MembershipFulfilment($purchases,$members,$bridge);
 $input=['request_id'=>bin2hex(random_bytes(16)),'account_type'=>'family','plan'=>'annual','terms_accepted'=>true,'permanent_acknowledged'=>true,'buyer'=>['email'=>'owner@example.test','email_confirm'=>'owner@example.test','name'=>'Test adult','country'=>'Türkiye','city'=>'İstanbul','address'=>'Example address','billing'=>'individual']];
 rejectTransfer(fn()=>$checkout->create(array_replace($input,['permanent_acknowledged'=>false]),'test',time()),'CONSENT_REQUIRED');$order=$checkout->create($input,'test',time());verifyTransfer($order['amount_minor']===20000&&$order['currency']==='USD');verifyTransfer($checkout->create($input,'test',time())['order_id']===$order['order_id']);rejectTransfer(fn()=>$checkout->create(array_replace($input,['plan'=>'monthly']),'test',time()),'REQUEST_REUSED');rejectTransfer(fn()=>$fulfilment->fulfil($order['order_id']),'PAYMENT_REQUIRED');rejectTransfer(fn()=>$checkout->confirm($order['order_id'],'BANK-REF-100','USD',19999,$settings),'BANK_SALE_MISMATCH');verifyTransfer((int)$store->query('SELECT COUNT(*) FROM membership_rights')->fetchColumn()===0);
 $checkout->confirm($order['order_id'],'BANK-REF-100','USD',20000,$settings);$group=$fulfilment->fulfil($order['order_id']);verifyTransfer($fulfilment->fulfil($order['order_id'])['id']===$group['id']);verifyTransfer(count($purchases->unfulfilled())===0);$owner=$purchases->order($order['order_id'])['account_id'];verifyTransfer(count($members->learners($group['id'],$owner,time()))===1);
 for($i=1;$i<=4;$i++)$members->invite($group['id'],$owner,"learner$i@example.test","learner$i@example.test",true,time());while($members->work($bridge,time())){}
 $mail=new class implements \Horizons\Mailer{public array $addresses=[];public function code(string $email,string $code,string $locale):void{$this->addresses[]=$email;verifyTransfer(preg_match('/^[0-9]{8}$/D',$code)===1);}};$service=new \Horizons\MembershipService($store,$crypto,$mail);while($service->deliver()){}verifyTransfer(count(array_unique($mail->addresses))===5);verifyTransfer((int)$store->query('SELECT COUNT(DISTINCT account_id) FROM membership_rights')->fetchColumn()===5);
 $conflict=$input;$conflict['request_id']=bin2hex(random_bytes(16));$conflict['buyer']['email']=$conflict['buyer']['email_confirm']='learner1@example.test';rejectTransfer(fn()=>$checkout->create($conflict,'test',time()),'EMAIL_ALREADY_ASSIGNED');
 $renew=$input;$renew['request_id']=bin2hex(random_bytes(16));$renewOrder=$checkout->create($renew,'test',time());$checkout->confirm($renewOrder['order_id'],'BANK-REF-RENEW','USD',20000,$settings);$renewed=$fulfilment->fulfil($renewOrder['order_id']);verifyTransfer($renewed['id']===$group['id']&&(int)$renewed['expires_at']>(int)$group['expires_at']);verifyTransfer($fulfilment->fulfil($renewOrder['order_id'])['expires_at']===$renewed['expires_at']);verifyTransfer(count($members->learners($group['id'],$owner,time()))===5&&$purchases->order($renewOrder['order_id'])['account_id']===$owner);verifyTransfer(!$service->deliver());
 $another=$input;$another['request_id']=bin2hex(random_bytes(16));$another['buyer']['email']=$another['buyer']['email_confirm']='other@example.test';$other=$checkout->create($another,'test',time());rejectTransfer(fn()=>$checkout->confirm($other['order_id'],'BANK-REF-100','USD',20000,$settings),'BANK_RECEIPT_REUSED');verifyTransfer($purchases->order($other['order_id'])['status']==='pending');verifyTransfer(!str_contains(file_get_contents($root.'/billing.sqlite'),'Example address'));
 echo "PASS: exact paid transfer, durable retry, bank receipt uniqueness, five independent family accounts, encrypted billing, renewal preserves roster. No real bank or SMTP used.\n";
}finally{unset($service,$bridge,$store,$fulfilment,$members,$purchases,$checkout);foreach(glob($root.'/*')as $f)if(is_file($f))unlink($f);rmdir($root.'/public_html');rmdir($root);}
