import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {webcrypto,generateKeyPairSync,sign,randomBytes} from 'node:crypto';
const {publicKey,privateKey}=generateKeyPairSync('ed25519');
const issuer=publicKey.export({format:'der',type:'spki'}).subarray(-32).toString('base64');
const rsa=await webcrypto.subtle.generateKey({name:'RSA-OAEP',hash:'SHA-256',modulusLength:2048,publicExponent:new Uint8Array([1,0,1])},true,['encrypt','decrypt']);
const spki=Buffer.from(await webcrypto.subtle.exportKey('spki',rsa.publicKey));const key=randomBytes(32),product='horizons-arabic-level1';
const wrapped=await webcrypto.subtle.encrypt({name:'RSA-OAEP',label:new TextEncoder().encode(product)},rsa.publicKey,key);
const identity={device_id:'a'.repeat(64),public_key:spki.toString('base64'),privateKey:rsa.privateKey};
const ctx=vm.createContext({crypto:webcrypto,TextEncoder,TextDecoder,Uint8Array,Date,performance,atob,btoa,console});
const source=await readFile('src/workbook-web/license-core.js','utf8');const module=new vm.SourceTextModule(source+'\nexport {clockTime};',{context:ctx});
await module.link(async id=>{const values=id==='./web-config.js'?{PRODUCT:product,ISSUER_PUBLIC_KEY:issuer,ACTIVATION_URL:'/activation'}:{decodeContent:()=>{}};return new vm.SyntheticModule(Object.keys(values),function(){for(const [k,v] of Object.entries(values))this.setExport(k,v)},{context:ctx});});await module.evaluate();
const iso=t=>new Date(t).toISOString().replace('.000Z','Z');const now=Math.floor(Date.now()/1000)*1000;
const base={schema:4,product,license_id:'member_test',device_id:identity.device_id,public_key_sha256:Buffer.from(await webcrypto.subtle.digest('SHA-256',spki)).toString('hex'),wrapped_key:Buffer.from(wrapped).toString('base64'),max_devices:0,issued_at:iso(now-10000),purchase_email:'test@example.test',account_id:'acct_test',plan:'lifetime',channel:'membership',starts_at:iso(now-20000),expires_at:null,device_policy:'any_device',account_type:'family',lease_expires_at:iso(now+600000)};
const envelope=l=>{const raw=Buffer.from(JSON.stringify(l));return {payload:raw.toString('base64'),signature:sign(null,raw,privateKey).toString('base64')}};
const access=await module.namespace.validateAndUnlock(envelope(base),identity);assert.equal(access.license.account_id,'acct_test');
for(const changes of [{max_devices:3},{device_policy:'three'},{account_type:'institution'},{lease_expires_at:iso(now+2*86400000)}])await assert.rejects(module.namespace.validateAndUnlock(envelope({...base,...changes}),identity),/LICENSE_INVALID/);
const old={...base,schema:3,channel:'direct',max_devices:3};delete old.device_policy;delete old.account_type;delete old.lease_expires_at;await module.namespace.validateAndUnlock(envelope(old),identity);
const expired=await module.namespace.validateAndUnlock(envelope({...base,lease_expires_at:iso(now-1000)}),identity);assert.throws(()=>module.namespace.clockTime(expired,{clock:{issued:now-10000,seen:now-10000}}),/MEMBERSHIP_CHECK_REQUIRED/);
console.log('PASS: real WebCrypto schema-4 licence, invalid policies rejected, legacy schema-3 compatibility, lifetime offline lease enforced.');
