// Upgrade a previously saved authorized public demo, preserving progress and offline assets.
const {chromium}=require('playwright');const fs=require('fs'),http=require('http'),path=require('path');
const assert=require('node:assert/strict');
for(const key of ['HZN_DEMO_BEFORE_ROOT','HZN_DEMO_AFTER_ROOT','HZN_CHROMIUM_EXECUTABLE'])if(!process.env[key])throw Error('Set '+key);
const output=path.resolve(process.env.HZN_QA_OUTPUT||'focus-offline-output');fs.mkdirSync(output,{recursive:true});
const folders={before:path.dirname(process.env.HZN_DEMO_BEFORE_ROOT),after:path.dirname(process.env.HZN_DEMO_AFTER_ROOT)};
async function until(check,timeout=20000){const end=Date.now()+timeout;while(Date.now()<end){if(await check())return;await new Promise(resolve=>setTimeout(resolve,50));}throw Error('Timed out waiting for worker state');}
(async()=>{let kind='before';const requests=[];
 const s=http.createServer((req,res)=>{let p=path.join(folders[kind],decodeURIComponent(new URL(req.url,'http://localhost').pathname));requests.push({kind,path:req.url});try{if(fs.statSync(p).isDirectory())p=path.join(p,'index.html');res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.json':'application/json','.html':'text/html','.svg':'image/svg+xml','.png':'image/png','.mp3':'audio/mpeg','.webp':'image/webp'}[path.extname(p)]||'application/octet-stream'));res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end('Missing')}});await new Promise(r=>s.listen(0,'127.0.0.1',r));
 const b=await chromium.launch({executablePath:process.env.HZN_CHROMIUM_EXECUTABLE,args:['--single-process','--no-zygote'],headless:true});const context=await b.newContext();let p=await context.newPage();const url='http://localhost:'+s.address().port+'/try/?lang=ar';const results={errors:[]};p.on('pageerror',e=>results.errors.push(e.message));
 try{await p.goto(url);await p.waitForFunction(()=>window.HORIZONS_BOOT?.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller,{timeout:20000});
 results.beforeSave=await p.evaluate(()=>window.HORIZONS_OFFLINE.prepare('baa'));
 await p.locator('#course-nav [data-course="catalog"]').click();await p.locator('[data-chapter="baa"]').click();await p.locator('#next').click();await p.locator('#next').click();
 results.beforeProgress=await p.evaluate(()=>JSON.parse(localStorage.getItem('horizons-arabic-level1|demo|1')));results.beforeCaches=await p.evaluate(()=>caches.keys());
 kind='after';await p.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update()});await until(()=>p.evaluate(async()=>!!(await navigator.serviceWorker.getRegistration()).waiting));results.updateWaitsForOpenTab=await p.locator('body').evaluate(n=>!n.classList.contains('hzn-focus'));
 await p.close();p=await context.newPage();await p.goto(new URL('/',url).href);await until(()=>p.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration('/try/');return r&&!r.waiting&&r.active?.state==='activated'}));await p.goto(url);await p.waitForFunction(()=>window.HORIZONS_BOOT?.ready&&document.body.classList.contains('hzn-focus'),{timeout:20000});results.newShell=true;results.harness='Async worker predicates explicitly awaited; earlier Playwright async waitForFunction produced a false readiness signal';results.activeNewWorkbook=await p.evaluate(async()=>{const r=await fetch('workbook.js');const text=await r.text();return {focusMarker:text.includes('WORKBOOK_FOCUS_BEGIN'),sha256:[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))].map(x=>x.toString(16).padStart(2,'0')).join('')}});
 results.afterProgress=await p.evaluate(()=>JSON.parse(localStorage.getItem('horizons-arabic-level1|demo|1')));results.afterCaches=await p.evaluate(()=>caches.keys());
 await p.locator('#hzn-resume').click();results.resumeLabel=await p.locator('#page-label').innerText();
 const beforeCount=requests.length;await context.setOffline(true);await p.reload();await p.waitForFunction(()=>window.HORIZONS_BOOT?.ready);await p.locator('#hzn-resume').click();results.offlineResume=await p.locator('#page-label').innerText();results.offlineImage=await p.locator('.sentence-scene img').evaluate(x=>x.complete&&x.naturalWidth>0);
 const audioPath=Object.keys(JSON.parse(fs.readFileSync(path.join(process.env.HZN_DEMO_AFTER_ROOT,'demo-asset-manifest.json'))).files).find(x=>x.includes('/word.baa-')&&x.endsWith('.mp3'));
 results.offlineAudio=await p.evaluate(async path=>{const r=await fetch(path);return{status:r.status,bytes:(await r.arrayBuffer()).byteLength}},audioPath);
 results.offlineNetworkRequests=requests.length-beforeCount;results.progressPreserved=JSON.stringify(results.beforeProgress)===JSON.stringify(results.afterProgress);
 assert.equal(results.progressPreserved,true);assert.equal(results.updateWaitsForOpenTab,true);assert.equal(results.offlineImage,true);assert.equal(results.offlineAudio.status,200);assert.equal(results.offlineNetworkRequests,0);assert.deepEqual(results.errors,[]);assert.equal(results.activeNewWorkbook.sha256,JSON.parse(fs.readFileSync(path.join(process.env.HZN_DEMO_AFTER_ROOT,'demo-asset-manifest.json'))).files['workbook.js'].sha256);
 fs.writeFileSync(path.join(output,'focus-offline-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({...results,beforeProgress:undefined,afterProgress:undefined}));
 }catch(error){results.failure=String(error);results.page=await p.evaluate(()=>({ready:window.HORIZONS_BOOT,focus:document.body.classList.contains('hzn-focus'),body:document.body.textContent.slice(0,500)}));fs.writeFileSync(path.join(output,'focus-offline-results.json'),JSON.stringify(results,null,2));throw error;}finally{await b.close();s.close()}
})().catch(e=>{console.error(e);process.exit(1)});
