<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/checkout/ManualOrders.php';require dirname(__DIR__).'/src/travel-kit/TravelDelivery.php';
$fixture=$argv[1];$zip=$argv[2];$root=dirname(__DIR__);$private=$fixture.'/horizons-travel-delivery';mkdir($private,0700,true);$key=random_bytes(32);$now=1790964000;
$manifest=json_decode(file_get_contents($root.'/release-assets/travel-kit-2.0.0/product.json'),true);copy($zip,$private.'/'.$manifest['filename']);file_put_contents($private.'/product.json',json_encode($manifest));
$catalog=json_decode(file_get_contents($root.'/src/commerce/products.json'),true);$orders=new HorizonsCheckout\ManualOrders($fixture.'/manual-orders.sqlite',$key,$catalog);
function check(bool $x,string $label):void{if(!$x)throw new RuntimeException('FAIL '.$label);echo 'PASS '.$label."\n";}
function reject(callable $f,string $expected):void{try{$f();}catch(RuntimeException $e){check($e->getMessage()===$expected,$expected);return;}throw new RuntimeException('Expected rejection '.$expected);}
$input=['request_id'=>str_repeat('a',32),'product'=>'travel-agent-client-kit','offer'=>'single-business','locale'=>'ar','terms_accepted'=>true,'privacy_read'=>true,'buyer'=>['first_name'=>'TEST','last_name'=>'Fixture','email'=>'test@example.invalid','email_confirm'=>'test@example.invalid','phone'=>'+900000000000','country'=>'Türkiye','city'=>'Istanbul','billing'=>'individual']];
$a=$orders->create($input,'test-client','127.0.0.1',$now);$b=$orders->create($input,'test-client','127.0.0.1',$now);check($a['reference']===$b['reference'],'idempotent order');
$db=new PDO('sqlite:'.$fixture.'/manual-orders.sqlite');$cipher=$db->query('SELECT payload FROM manual_orders')->fetchColumn();check(!str_contains($cipher,'test@example.invalid'),'encrypted buyer storage');$bytes=base64_decode($cipher);$order=json_decode(sodium_crypto_secretbox_open(substr($bytes,24),substr($bytes,0,24),$key),true);$order['reference']=$a['reference'];check($order['payment_status']==='not_collected'&&$order['fulfilment_status']==='manual','no charge or automatic delivery');
$delivery=new HorizonsTravel\TravelDelivery($private,$key);reject(fn()=>$delivery->issue($order,'test@example.invalid','receipt-test',false,$now),'PAYMENT_CONFIRM_REQUIRED');reject(fn()=>$delivery->issue($order,'other@example.invalid','receipt-test',true,$now),'EMAIL_MISMATCH');
$link=$delivery->issue($order,'test@example.invalid','receipt-test',true,$now);$token=parse_url($link['url'],PHP_URL_FRAGMENT);check($link['expires_at']===$now+7*86400&&$link['max_downloads']===5,'seven-day five-download link');check($delivery->claim($token,$now)['sha256']===$manifest['sha256'],'private product claim');for($i=0;$i<4;$i++)$delivery->claim($token,$now);reject(fn()=>$delivery->claim($token,$now),'LINK_INVALID');
$link=$delivery->issue($order,'test@example.invalid','receipt-test',true,$now);$token2=parse_url($link['url'],PHP_URL_FRAGMENT);reject(fn()=>$delivery->claim($token,$now),'LINK_INVALID');reject(fn()=>$delivery->claim($token2,$now+7*86400),'LINK_INVALID');$other=$order;$other['reference']='HZN-M-20261002-0123456789ABCDEF';reject(fn()=>$delivery->issue($other,'test@example.invalid','receipt-test',true,$now),'RECEIPT_REUSED');
$d=new PDO('sqlite:'.$private.'/delivery.sqlite');$raw=json_encode($d->query('SELECT * FROM deliveries')->fetchAll(PDO::FETCH_ASSOC));check(!str_contains($raw,$token2)&&!str_contains($raw,'test@example.invalid'),'token and email stored as hashes');echo "Manual delivery test complete; no external email or payment sent.\n";
