import {resendMembershipCode,checkMembershipCode,setupMembershipPassword,refreshMembership,requestMembership,signOut} from './license-core.js';
import {mountMembershipManager} from './membership-manager.js';
const dictionaries={
 ar:{activate:'تفعيل الاشتراك برمز البريد',email:'البريد الإلكتروني',code:'رمز التفعيل من 8 أرقام',continue:'متابعة',verified:'تم التحقق من البريد. اختر كلمة مرور من 12 حرفًا على الأقل.',password:'كلمة المرور',confirm_password:'تأكيد كلمة المرور',title:'المتعلمون في اشتراكي',add:'إضافة متعلم',email_confirm:'أعد كتابة البريد للتأكيد',permanent_warning:'تنبيه: بريد المتعلم في الحساب العائلي ثابت ولا يمكن حذفه أو استبداله، حتى لو لم يُفعّل الحساب بعد.',permanent_consent:'تحققت من البريد وأوافق على تثبيته نهائيًا.',remove:'حذف المتعلم',remove_warning:'سيتوقف وصول هذا المتعلم ضمن اشتراك المؤسسة. تأكيد الحذف؟',cancel:'إلغاء',removed:'أُلغي وصول المتعلم.',invited:'أُضيف المتعلم وسيصله رمز التفعيل بالبريد.',error:'تعذّر إكمال العملية. تحقق من البيانات والاتصال ثم حاول مجددًا.',mismatch:'كلمتا المرور غير متطابقتين.',working:'جارٍ التحقق…',done:'تم التفعيل. يمكنك فتح الكراسة.',resend:'إرسال رمز جديد',sent:'إذا كان البريد مرتبطًا باشتراك صالح فسيصله رمز التفعيل. تحقق من البريد غير المرغوب أيضًا.',back:'العودة إلى رمز التفعيل'},
 en:{activate:'Activate with your email code',email:'Email address',code:'8-digit activation code',continue:'Continue',verified:'Email verified. Choose a password of at least 12 characters.',password:'Password',confirm_password:'Confirm password',title:'Learners in my subscription',add:'Add learner',email_confirm:'Enter the email again',permanent_warning:'Family learner emails are permanent. They cannot be deleted or replaced, including before activation.',permanent_consent:'I checked the email and accept its permanent assignment.',remove:'Remove learner',remove_warning:'This learner will lose access through this institution. Confirm removal?',cancel:'Cancel',removed:'Learner access revoked.',invited:'Learner added. An activation code will arrive by email.',error:'Unable to complete this action. Check the details and connection, then try again.',mismatch:'Passwords do not match.',working:'Checking…',done:'Activated. You can open the workbook.',resend:'Send another code',sent:'If this email has an eligible subscription, an activation code will arrive. Check your spam folder too.',back:'Back to activation code'},
 tr:{activate:'E-posta koduyla etkinleştir',email:'E-posta adresi',code:'8 haneli etkinleştirme kodu',continue:'Devam',verified:'E-posta doğrulandı. En az 12 karakterli bir parola belirleyin.',password:'Parola',confirm_password:'Parolayı doğrulayın',title:'Aboneliğimdeki öğrenciler',add:'Öğrenci ekle',email_confirm:'E-posta adresini tekrar yazın',permanent_warning:'Aile hesabındaki öğrenci e-postaları kalıcıdır. Etkinleştirme öncesinde bile silinemez veya değiştirilemez.',permanent_consent:'E-postayı kontrol ettim ve kalıcı olarak atanmasını kabul ediyorum.',remove:'Öğrenciyi kaldır',remove_warning:'Öğrencinin bu kurum üzerinden erişimi sona erecek. Onaylıyor musunuz?',cancel:'İptal',removed:'Öğrenci erişimi kaldırıldı.',invited:'Öğrenci eklendi. Etkinleştirme kodu e-posta ile gönderilecek.',error:'İşlem tamamlanamadı. Bilgileri ve bağlantınızı kontrol edip tekrar deneyin.',mismatch:'Parolalar eşleşmiyor.',working:'Kontrol ediliyor…',done:'Etkinleştirildi. Çalışma kitabını açabilirsiniz.',resend:'Yeni kod gönder',sent:'Bu e-postanın geçerli bir aboneliği varsa etkinleştirme kodu gönderilir. Spam klasörünü de kontrol edin.',back:'Etkinleştirme koduna dön'}
};
const $=id=>document.getElementById(id);let setupToken='',manager=null,managerLanguage='',getLanguage=()=>document.documentElement.lang,busy=false;
const words=()=>dictionaries[getLanguage()]||dictionaries.en;
function status(text){$('status').textContent=text;}
export function updateMembershipUI(state,lang){
 const labels=dictionaries[lang]||dictionaries.en;document.querySelectorAll('[data-m]').forEach(n=>{n.textContent=labels[n.dataset.m];n.lang=dictionaries[lang]?lang:'en';});
 const host=$('membership-manager');if(!host)return;host.hidden=!(state.activated&&state.license?.schema===4);
 if(host.hidden){manager?.destroy();manager=null;return;}
 if(!manager||managerLanguage!==lang){manager?.destroy();managerLanguage=lang;host.lang=dictionaries[lang]?lang:'en';manager=mountMembershipManager(host,{list:()=>requestMembership('list'),invite:x=>requestMembership('invite',x),remove:member_id=>requestMembership('remove',{member_id})},labels);}
}
export async function initializeMembershipUI(refresh,language){
 getLanguage=language;
 async function run(form,fn){if(busy)return;busy=true;const buttons=[...form.querySelectorAll('button')];buttons.forEach(x=>x.disabled=true);status(words().working);try{await fn();}catch{status(words().error);}finally{busy=false;buttons.forEach(x=>x.disabled=false);}}
 $('membership-resend').onclick=()=>{if(!$('membership-email').reportValidity())return;run($('membership-code-form'),async()=>{await resendMembershipCode($('membership-email').value.trim());status(words().sent);});};
 $('membership-back').onclick=()=>{if(busy)return;setupToken='';$('membership-password').value='';$('membership-confirm').value='';$('membership-password-form').hidden=true;$('membership-code-form').hidden=false;$('membership-code').focus();};
 $('membership-code-form').onsubmit=e=>{e.preventDefault();run(e.currentTarget,async()=>{const r=await checkMembershipCode({email:$('membership-email').value.trim(),code:$('membership-code').value.trim()});setupToken=r.setup_token;$('membership-code').value='';$('membership-code-form').hidden=true;$('membership-password-form').hidden=false;status(words().verified);$('membership-password').focus();});};
 $('membership-password-form').onsubmit=e=>{e.preventDefault();if($('membership-password').value!==$('membership-confirm').value)return status(words().mismatch);run(e.currentTarget,async()=>{try{await setupMembershipPassword({setup_token:setupToken,new_password:$('membership-password').value});setupToken='';$('membership-password-form').hidden=true;await refresh();status(words().done);$('open').focus();}finally{$('membership-password').value='';$('membership-confirm').value='';}});};
 async function renew(){try{await refreshMembership();}catch(e){if(e.message==='ENTITLEMENT_EXPIRED')await signOut();}await refresh();}
 addEventListener('online',()=>renew().catch(()=>{}));document.addEventListener('visibilitychange',()=>{if(!document.hidden&&navigator.onLine)renew().catch(()=>{});});setInterval(()=>{if(navigator.onLine)renew().catch(()=>{});},15*60000);
 try{await refreshMembership();}catch(e){if(e.message==='ENTITLEMENT_EXPIRED')await signOut();}
}
