import {requestCode,verifyCode,getState,signOut} from './license-core.js';
import {VERSION} from './web-config.js';
import {names,language,dictionaries,translate,registerWorker,workerMessage,installControl} from './web-ui.js';
const $=id=>document.getElementById(id);
let lang=language(),portal={},words={},challenge='',busy=false,registration,state,download=false;
const t=k=>translate(portal,lang,k),w=(k,v)=>translate(words,lang,k,v);
function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':''}
function fail(error){const key={OTP_INVALID:'invalid',DEVICE_LIMIT:'limit',PILOT_LIMIT_REACHED:'pilotFull',INVALID_EMAIL:'emailInvalid',INVITATION_INVALID:'invitationInvalid',ENTITLEMENT_EXPIRED:'expired',CLOCK_ROLLBACK:'clockRollback',CLOCK_AHEAD:'clockAhead',RATE_LIMITED:'rateLimited',PURCHASE_UNAVAILABLE:'purchaseMissing'}[error.message];status(key?t(key):w(['BROWSER_UNSUPPORTED','WORKER_TIMEOUT'].includes(error.message)?'unsupported':error.message==='DOWNLOAD_CANCELLED'?'cancelled':'offlineFailed'),true)}
function localize(){document.documentElement.lang=lang;document.documentElement.dir=['ar','he','fa','ur'].includes(lang)?'rtl':'ltr';document.querySelectorAll('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));document.querySelectorAll('[data-w]').forEach(el=>{el.textContent=w(el.dataset.w);el.lang=words[lang]?.[el.dataset.w]?lang:'en'});$('language').value=lang;$('language').ariaLabel=t('language');$('demo').href='../try/?lang='+lang;$('open').href='app/index.html?lang='+lang;try{localStorage.setItem('horizons-interface-language',lang)}catch{}renderState();}
function renderState(){if(!state)return;$('active').hidden=!state.activated;$('activation').hidden=state.activated;$('save-all').disabled=!state.activated||download;$('active-email').textContent=state.license?.purchase_email||'';const l=state.license;$('entitlement').textContent=l?t(l.plan)+' · '+(l.expires_at?t('expires')+': '+new Intl.DateTimeFormat(lang,{dateStyle:'medium',timeStyle:'short'}).format(new Date(l.expires_at)):t('noExpiry')):'';}
const worker=()=>navigator.serviceWorker.controller||registration?.active;
async function refresh(){state=await getState();renderState();if(state.error&&state.error!=='ACTIVATION_REQUIRED')fail(Error(state.error));if(worker()){const s=await workerMessage(worker(),{type:'offline-state'});$('offline-state').textContent=w('savedStatus',{saved:s.savedFiles,total:s.totalFiles,size:(s.savedBytes/1048576).toFixed(1)});}}
function setBusy(value){busy=value;$('send').disabled=value;$('verify').disabled=value;}
$('email-form').onsubmit=async e=>{e.preventDefault();if(busy)return;setBusy(true);challenge='';$('code-form').hidden=true;status(t('working'));try{if(!worker())throw Error('WORKER_TIMEOUT');const result=await requestCode({email:$('email').value.trim(),locale:lang,invitation_token:$('invitation').value.trim()});challenge=result.challenge_id;$('code-form').hidden=false;$('code').value='';status(t('sent'));$('code').focus();}catch(error){fail(error)}finally{setBusy(false)}};
for(const id of ['email','invitation'])$(id).oninput=()=>{challenge='';$('code-form').hidden=true;};
$('code-form').onsubmit=async e=>{e.preventDefault();if(busy||!challenge)return;setBusy(true);status(t('working'));try{await verifyCode({challenge_id:challenge,code:$('code').value.trim()});$('code').value='';$('code-form').hidden=true;status(t('activated'));await refresh();$('open').focus();}catch(error){fail(error)}finally{setBusy(false)}};
$('language').onchange=()=>{lang=$('language').value;localize();refresh().catch(fail)};
$('signout').onclick=async()=>{if(!confirm(w('signoutConfirm')))return;await signOut();await refresh();status('');};
$('save-all').onclick=async()=>{if(download)return;download=true;renderState();$('cancel').hidden=false;$('progress').hidden=false;try{await navigator.storage?.persist?.();await workerMessage(worker(),{type:'cache-group',group:'all',version:VERSION},({done,total})=>{$('progress').max=total;$('progress').value=done;status(w('saving',{done,total}))});status(w('saved'))}catch(error){fail(error)}finally{download=false;$('cancel').hidden=true;$('progress').hidden=true;await refresh().catch(fail)}};
$('cancel').onclick=()=>workerMessage(worker(),{type:'cancel-download'}).catch(fail);
$('verify-saved').onclick=async()=>{if(download)return;download=true;$('verify-saved').disabled=true;renderState();try{const result=await workerMessage(worker(),{type:'verify-downloads'},({done,total})=>status(w('saving',{done,total})));status(w('verifiedSaved',{damaged:result.damaged}));}catch(error){fail(error)}finally{download=false;$('verify-saved').disabled=false;await refresh().catch(fail)}};
$('clear').onclick=async()=>{if(!confirm(w('removeConfirm')))return;try{await workerMessage(worker(),{type:'clear-downloads'});await refresh()}catch(error){fail(error)}};
async function start(){try{[portal,words]=await dictionaries();for(const [code,name]of Object.entries(names)){const o=document.createElement('option');o.value=code;o.textContent=name;$('language').append(o)}localize();installControl($('install'),$('install-help'),w);status(w('loading'));registration=await registerWorker();await refresh();if(!state?.error||state.error==='ACTIVATION_REQUIRED')status('');if(registration.waiting)status(w('updateReady'));const reason=new URL(location.href).searchParams.get('reason');if(reason)fail(Error(reason));}catch(error){status(words.en?w('unsupported'):'تعذّر فتح الكراسة. جرّب متصفحًا حديثًا واتصالًا آمنًا. / Unable to open the workbook. Use an updated browser and HTTPS.',true);}}
addEventListener('online',()=>{registration?.update().catch(()=>{});refresh().catch(fail)});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&registration)refresh().catch(fail)});
start();
