import {initializeMembershipUI,updateMembershipUI,configureMembershipLocales} from './membership-ui.js';
import {requestCode,verifyCode,loginPassword,getState,signOut} from './license-core.js';
import {VERSION} from './web-config.js';
import {names,language,direction,dictionaries,translate,registerWorker,workerMessage,installControl} from './web-ui.js';
const $=id=>document.getElementById(id);
let lang=language(),portal={},words={},challenge='',busy=false,registration,state,download=false;
const t=k=>translate(portal,lang,k),w=(k,v)=>translate(words,lang,k,v);
function status(text,error=false){const el=$('status');el.textContent=text;el.className=error?'error':'';delete el.dataset.uiStatus;delete el.dataset.membershipStatus}
function show(key,kind='web',error=false,values={}){status(kind==='portal'?t(key):w(key,values),error);$('status').dataset.uiStatus=JSON.stringify({key,kind,error,values})}
function fail(error){if(error.message==='MEMBERSHIP_CHECK_REQUIRED')return show('membershipCheck','web',true);if(error.message==='PILOT_LIMIT_REACHED')return show('pilotFull','web',true);if(error.status===429)return show('rateLimited','portal',true);const passwordKey={PASSWORD_INVALID:'passwordInvalid',PASSWORD_WEAK:'passwordWeak',DEVICE_ID_CONFLICT:'deviceConflict'}[error.message];if(passwordKey)return show(passwordKey,'web',true);const key={OTP_INVALID:'invalid',DEVICE_LIMIT:'limit',INVALID_EMAIL:'emailInvalid',INVITATION_INVALID:'invitationInvalid',ENTITLEMENT_EXPIRED:'expired',CLOCK_ROLLBACK:'clockRollback',CLOCK_AHEAD:'clockAhead',RATE_LIMITED:'rateLimited',PURCHASE_UNAVAILABLE:'purchaseMissing'}[error.message];show(key||(['BROWSER_UNSUPPORTED','WORKER_TIMEOUT'].includes(error.message)?'unsupported':error.message==='DOWNLOAD_CANCELLED'?'cancelled':'offlineFailed'),key?'portal':'web',true)}
function localize(){const priorStatus=$('status').dataset.uiStatus;document.documentElement.lang=lang;document.documentElement.dir=direction(lang);document.querySelectorAll('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));document.querySelectorAll('[data-w]').forEach(el=>{el.textContent=w(el.dataset.w);el.lang=words[lang]?.[el.dataset.w]?lang:'en'});document.title='HORIZONS · '+w('title');$('progress').setAttribute('aria-label',w('downloadProgress'));if($('install-help').dataset.installHelp)$('install-help').textContent=w($('install-help').dataset.installHelp);updateMembershipUI(state||{activated:false},lang);if(priorStatus){const v=JSON.parse(priorStatus);show(v.key,v.kind,v.error,v.values)}$('language').value=lang;$('language').ariaLabel=t('language');$('demo').href='../try/?lang='+lang;$('open').href='app/index.html?lang='+lang;try{localStorage.setItem('horizons-interface-language',lang)}catch{}renderState();}
function renderState(){if(!state)return;updateMembershipUI(state,lang);$('active').hidden=!state.activated;$('activation').hidden=state.activated;$('save-all').disabled=!state.activated||download;$('active-email').textContent=state.license?.purchase_email||'';const l=state.license;$('entitlement').textContent=l?t(l.plan)+' · '+(l.expires_at?t('expires')+': '+new Intl.DateTimeFormat(lang,{dateStyle:'medium',timeStyle:'short'}).format(new Date(l.expires_at)):t('noExpiry')):'';}
const worker=()=>navigator.serviceWorker.controller||registration?.active;
async function refresh(){state=await getState();renderState();if(state.error&&state.error!=='ACTIVATION_REQUIRED')fail(Error(state.error));if(worker()){const s=await workerMessage(worker(),{type:'offline-state'});$('offline-state').textContent=w('savedStatus',{saved:s.savedFiles,total:s.totalFiles,size:new Intl.NumberFormat(lang,{style:'unit',unit:'megabyte',unitDisplay:'short',maximumFractionDigits:1}).format(s.savedBytes/1048576)});}}
function setBusy(value){busy=value;$('send').disabled=value;$('verify').disabled=value;$('password-submit').disabled=value;}
$('password-form').onsubmit=async e=>{e.preventDefault();if(busy)return;setBusy(true);show('working','portal');try{if(!worker())throw Error('WORKER_TIMEOUT');await loginPassword({email:$('login-email').value.trim(),password:$('login-password').value});show('activated','portal');await refresh();$('open').focus();}catch(error){fail(error)}finally{$('login-password').value='';setBusy(false)}};
$('code-option').ontoggle=()=>{if($('code-option').open&&!$('email').value)$('email').value=$('login-email').value};
$('email-form').onsubmit=async e=>{e.preventDefault();if(busy)return;setBusy(true);challenge='';$('code-form').hidden=true;show('working','portal');try{if(!worker())throw Error('WORKER_TIMEOUT');const result=await requestCode({email:$('email').value.trim(),locale:lang,invitation_token:$('invitation').value.trim()});challenge=result.challenge_id;$('code-form').hidden=false;$('code').value='';show('sent','portal');$('code').focus();}catch(error){fail(error)}finally{setBusy(false)}};
for(const id of ['email','invitation'])$(id).oninput=()=>{challenge='';$('code-form').hidden=true;};
$('code-form').onsubmit=async e=>{e.preventDefault();if(busy||!challenge)return;if($('new-password').value!==$('confirm-password').value)return show('passwordMismatch','web',true);setBusy(true);show('working','portal');try{await verifyCode({challenge_id:challenge,code:$('code').value.trim(),new_password:$('new-password').value});$('login-email').value=$('email').value;$('code').value='';$('code-form').hidden=true;$('code-option').open=false;show('activated','portal');await refresh();$('open').focus();}catch(error){fail(error)}finally{$('new-password').value='';$('confirm-password').value='';setBusy(false)}};
$('language').onchange=()=>{lang=$('language').value;localize();refresh().catch(fail)};
$('signout').onclick=async()=>{if(!confirm(w('signoutConfirm')))return;await signOut();await refresh();status('');};
$('save-all').onclick=async()=>{if(download)return;download=true;renderState();$('cancel').hidden=false;$('progress').hidden=false;try{await navigator.storage?.persist?.();await workerMessage(worker(),{type:'cache-group',group:'all',version:VERSION},({done,total})=>{$('progress').max=total;$('progress').value=done;show('saving','web',false,{done,total})});show('saved')}catch(error){fail(error)}finally{download=false;$('cancel').hidden=true;$('progress').hidden=true;await refresh().catch(fail)}};
$('cancel').onclick=()=>workerMessage(worker(),{type:'cancel-download'}).catch(fail);
$('verify-saved').onclick=async()=>{if(download)return;download=true;$('verify-saved').disabled=true;renderState();try{const result=await workerMessage(worker(),{type:'verify-downloads'},({done,total})=>show('saving','web',false,{done,total}));show('verifiedSaved','web',false,{damaged:result.damaged});}catch(error){fail(error)}finally{download=false;$('verify-saved').disabled=false;await refresh().catch(fail)}};
$('clear').onclick=async()=>{if(!confirm(w('removeConfirm')))return;try{await workerMessage(worker(),{type:'clear-downloads'});await refresh()}catch(error){fail(error)}};
async function start(){try{[portal,words]=await dictionaries();configureMembershipLocales(portal,words);for(const [code,name]of Object.entries(names)){const o=document.createElement('option');o.value=code;o.textContent=name;$('language').append(o)}localize();installControl($('install'),$('install-help'),w);show('loading');registration=await registerWorker();await initializeMembershipUI(refresh,()=>lang);await refresh();if(!state?.error||state.error==='ACTIVATION_REQUIRED')status('');if(registration.waiting)show('updateReady');const reason=new URL(location.href).searchParams.get('reason');if(reason)fail(Error(reason));}catch(error){status(words.en?w('unsupported'):'تعذّر فتح الكراسة. جرّب متصفحًا حديثًا واتصالًا آمنًا. / Unable to open the workbook. Use an updated browser and HTTPS.',true);}}
addEventListener('online',()=>{registration?.update().catch(()=>{});refresh().catch(fail)});
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&registration)refresh().catch(fail)});
start();
