export const names={en:'English',ar:'العربية',tr:'Türkçe',fr:'Français',es:'Español',de:'Deutsch',it:'Italiano',pt:'Português',nl:'Nederlands',ru:'Русский',uk:'Українська',pl:'Polski',cs:'Čeština',ro:'Română',hu:'Magyar',el:'Ελληνικά',sv:'Svenska',da:'Dansk',no:'Norsk',fi:'Suomi',bg:'Български',sr:'Српски',hr:'Hrvatski',he:'עברית',fa:'فارسی',ur:'اردو',hi:'हिन्दी',bn:'বাংলা',id:'Bahasa Indonesia',ms:'Bahasa Melayu',zh:'简体中文',ja:'日本語'};
export function normalizeLanguage(value){const code=String(value||'').trim().toLowerCase().replaceAll('_','-').split('-')[0];const normalized=({nb:'no',nn:'no',iw:'he'})[code]||code;return Object.hasOwn(names,normalized)?normalized:null}
export function direction(lang){return ['ar','he','fa','ur'].includes(normalizeLanguage(lang))?'rtl':'ltr'}
export function language(){let stored;try{stored=localStorage.getItem('horizons-interface-language')}catch{}return [new URL(location.href).searchParams.get('lang'),stored,...(navigator.languages||[navigator.language])].map(normalizeLanguage).find(Boolean)||'en'}
export async function dictionaries(){const base=new URL('./',import.meta.url);const responses=await Promise.all(['portal-locales.json','web-locales.json'].map(x=>fetch(new URL(x,base))));if(responses.some(x=>!x.ok))throw Error('LANGUAGE_UNAVAILABLE');return Promise.all(responses.map(x=>x.json()))}
export function translate(dict,lang,key,values={}){const locale=normalizeLanguage(lang)||'en';let result=dict[locale]?.[key]??dict.en?.[key]??key;const number=new Intl.NumberFormat(locale,{maximumFractionDigits:1});for(const[k,v]of Object.entries(values)){const value=typeof v==='number'?number.format(v):String(v);result=result.replaceAll('{'+k+'}',direction(locale)==='rtl'?'\u2068'+value+'\u2069':value)}return result}
export function workerMessage(worker,data,progress=()=>{},timeout=65000){return new Promise((resolve,reject)=>{const channel=new MessageChannel();let timer;const close=()=>{clearTimeout(timer);channel.port1.close()};const arm=()=>{clearTimeout(timer);timer=setTimeout(()=>{close();reject(Error('OFFLINE_TIMEOUT'))},timeout)};channel.port1.onmessage=({data:m})=>{arm();if(typeof m.done==='number')progress(m);if(m.ok===true){close();resolve(m)}else if(m.ok===false){close();reject(Error(m.error||'OFFLINE_FAILED'))}};arm();worker.postMessage(data,[channel.port2])})}
export async function registerWorker(){if(!navigator.serviceWorker||!isSecureContext)throw Error('BROWSER_UNSUPPORTED');const base=new URL('./',import.meta.url);const reg=await navigator.serviceWorker.register(new URL('sw.js',base),{type:'module',scope:base.pathname,updateViaCache:'none'});let timer;await Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('WORKER_TIMEOUT')),25000)})]).finally(()=>clearTimeout(timer));if(!navigator.serviceWorker.controller)await new Promise((resolve,reject)=>{const changed=()=>{if(navigator.serviceWorker.controller){clearTimeout(wait);navigator.serviceWorker.removeEventListener('controllerchange',changed);resolve()}};const wait=setTimeout(()=>{navigator.serviceWorker.removeEventListener('controllerchange',changed);reject(Error('WORKER_TIMEOUT'))},15000);navigator.serviceWorker.addEventListener('controllerchange',changed);changed()});reg.update().catch(()=>{});return reg}
export function installControl(button,help,t){let prompt;const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;if(standalone())button.hidden=true;addEventListener('beforeinstallprompt',e=>{e.preventDefault();prompt=e;button.hidden=false});addEventListener('appinstalled',()=>{button.hidden=true;help.hidden=true});button.onclick=async()=>{if(prompt){await prompt.prompt();await prompt.userChoice;prompt=null}else{delete help.dataset.updateReady;help.hidden=!help.hidden;help.dataset.installHelp=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)?'iphoneNote':/Android/.test(navigator.userAgent)?'androidNote':'installHelp';help.textContent=t(help.dataset.installHelp)}}}
