#!/usr/bin/env python3
"""Build the 1.4.5 public interface overlay, retaining every lesson/media hash.

Canonical translations: src/workbook-web/{web,portal}-locales.json.
The demo receives only its own UI strings, not account or paid lesson data.
No secrets, databases or owner vaults are read.
"""
import hashlib
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION = '1.4.5'
BASE_COMMIT = 'f720db2fe4fc49a5d6d246e563563fbafa5a4ce8'
OUT = ROOT / 'release-assets' / VERSION

def sha(data):
    return hashlib.sha256(data).hexdigest()

def read(path):
    return json.loads((ROOT / path).read_text())

def write(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')

def baseline(path):
    return sha(subprocess.check_output(['git', 'show', f'{BASE_COMMIT}:{path}'], cwd=ROOT))

def build():
    web = read('src/workbook-web/web-locales.json')
    portal = read('src/workbook-web/portal-locales.json')
    languages = set(read('src/commerce/account-locales.json'))
    assert set(web) == set(portal) == languages and len(languages) == 32
    for data in (web, portal):
        for lang, values in data.items():
            assert values.keys() == data['en'].keys(), (lang, 'incomplete keys')
            for key, value in values.items():
                assert isinstance(value, str) and value.strip(), (lang, key)
                assert sorted(re.findall(r'\{\w+\}', value)) == sorted(re.findall(r'\{\w+\}', data['en'][key])), (lang, key, 'placeholders')
    demo_map = dict(button='demoButton', title='demoTitle', install='install', save='demoSave',
                    cancel='cancel', clear='clear', close='close', note='offlineNote',
                    state='savedStatus', saving='saving', done='demoDone', cancelled='cancelled',
                    error='offlineFailed', unsupported='unsupported', help='installHelp',
                    offline='networkOffline', online='networkOnline', storage='storageUsage',
                    notPersistent='notPersistent', persistent='persistent', confirm='removeConfirm',
                    update='updateReady', busy='busy', checking='checking', progress='downloadProgress')
    demo_locales = {lang: {key: values[source] for key, source in demo_map.items()} for lang, values in web.items()}
    generated = OUT / 'files/try/demo-locales.js'
    generated.parent.mkdir(parents=True, exist_ok=True)
    generated.write_text('// Generated by scripts/build_interface_update.py.\n' +
                         'globalThis.HORIZONS_DEMO_LOCALES=' + json.dumps(demo_locales, ensure_ascii=False, separators=(',', ':')) + ';\n')
    before_demo = read('release-assets/demo-1.4.3/files/try/demo-asset-manifest.json')
    demo = json.loads(json.dumps(before_demo))
    paid = read('release-assets/1.4.4/files/learn/asset-manifest.json')
    paid['version'] = demo['version'] = VERSION
    demo_files = ['index.html', 'demo-pwa.js', 'workbook.js', 'release-config.js', 'sw.js']
    public = {f'try/{name}': f'src/demo-pwa/{name}' for name in demo_files}
    public['try/demo-locales.js'] = generated.relative_to(ROOT).as_posix()
    for target, source in public.items():
        name = target.removeprefix('try/')
        if name == 'sw.js':
            continue  # The service worker is not one of its own cache entries.
        data = (ROOT / source).read_bytes()
        demo['files'][name] = dict(demo['files'].get(name, {}), bytes=len(data), sha256=sha(data))
        demo['files'][name].setdefault('mime', 'application/javascript' if name.endswith('.js') else 'text/html')
    demo['shell'].append('demo-locales.js')
    for name, entry in before_demo['files'].items():
        if name.startswith('course/') or name == 'workbook-data.js':
            assert demo['files'][name] == entry, ('Curriculum changed', name)
    for name, data in [('learn/asset-manifest.json', paid), ('try/demo-asset-manifest.json', demo)]:
        path = OUT / 'files' / name
        write(path, data)
        public[name] = path.relative_to(ROOT).as_posix()
    paid_files = ['index.html', 'shell.css', 'shell.js', 'web-ui.js', 'pwa-client.js',
                  'membership-ui.js', 'membership-manager.js', 'portal-locales.json', 'web-locales.json', 'web-config.js']
    for name in paid_files:
        public['learn/' + name] = 'src/workbook-web/' + name
    # A worker content change triggers update detection; imported VERSION also changes.
    public['learn/sw.js'] = 'src/workbook-web/sw.js'
    files = {}
    for target, source in public.items():
        body = (ROOT / source).read_bytes()
        if target == 'try/demo-locales.js':
            before = None
        elif target == 'try/sw.js':
            before = baseline(source)
        elif target.startswith('try/') and target != 'try/demo-asset-manifest.json':
            before = before_demo['files'][target[4:]]['sha256']
        elif target == 'try/demo-asset-manifest.json':
            before = sha((ROOT / 'release-assets/demo-1.4.3/files/try/demo-asset-manifest.json').read_bytes())
        elif target == 'learn/asset-manifest.json':
            before = sha((ROOT / 'release-assets/1.4.4/files/learn/asset-manifest.json').read_bytes())
        else:
            before = baseline(source)
        files[target] = {'source': source, 'bytes': len(body), 'sha256': sha(body), 'before': before}
    # Manifests and worker update triggers are installed after all their dependencies.
    files = dict(sorted(files.items(), key=lambda item: (item[0].endswith('/sw.js'), 'manifest.json' in item[0], item[0])))
    requires = {name: baseline('src/workbook-web/' + name[6:]) for name in ['learn/license-core.js','learn/learner-store.js','learn/progress-sync-client.js']}
    write(OUT / 'interface-manifest.json', {'version': VERSION, 'requires': requires, 'files': files})
    report = dict(version=VERSION, languages=list(web), locale_keys=len(web['en']),
                  files=len(files), bytes=sum(entry['bytes'] for entry in files.values()),
                  paid_content_files_unchanged=len(paid['files']),
                  demo_curriculum_files_unchanged=sum(name.startswith('course/') or name == 'workbook-data.js' for name in demo['files']),
                  cover_unchanged=True, account_and_progress_storage_unchanged=True)
    write(OUT / 'build-report.json', report)
    print(json.dumps(report))

if __name__ == '__main__':
    build()
