"""Publish localized media blocks while preserving the existing product and commerce text."""
import hashlib,html,json,subprocess
from pathlib import Path
repo=Path(__file__).resolve().parents[1];locales=json.loads((repo/'scripts/workbook-video-locales.json').read_text());esc=html.escape
meta=json.loads((repo/'dist/workbook-video-release.json').read_text());assert meta['video_count']==32 and set(meta['languages'])==set(locales)
manpath=repo/'release-assets/global-currency-20261002/manifest.json';manifest=json.loads(manpath.read_text())
for lang,t in locales.items():
 path=repo/'dist'/lang/'product.html';prior=path.read_bytes();s=prior.decode();assert 'id="workbook-walkthrough"' not in s
 prefix=f'../assets/workbook-video/1.0.0/{lang}/';section=f'<section id="workbook-walkthrough" class="workbook-walkthrough" aria-labelledby="workbook-video-title"><h2 id="workbook-video-title">{esc(t["heading"])}</h2><video controls playsinline preload="none" width="1280" height="720" poster="{prefix}poster.jpg" aria-label="{esc(t["watch"])}"><source src="{prefix}walkthrough.mp4" type="video/mp4"><track kind="captions" src="{prefix}walkthrough.vtt" srclang="{lang}" label="{lang.upper()}"></video><p class="workbook-video-note">{esc(t["note"])}</p><div class="actions"><a class="button ghost" href="/try/?lang={lang}">{esc(t["try"])}</a></div><details class="workbook-video-transcript"><summary>{esc(t["watch"])}</summary><ol>'+''.join(f'<li><strong>{esc(step)}</strong><p>{esc(caption)}</p></li>' for step,caption in zip(t['steps'],t['captions']))+'</ol></details></section>'
 anchor='<section>';assert anchor in s;s=s.replace(anchor,section+anchor,1).replace('</head>','<link rel="stylesheet" href="../workbook-video.css?v=1.0.0"/></head>',1);path.write_text(s)
 entry=manifest['files']['public/'+lang+'/product.html'];allowed=entry['before'] if isinstance(entry['before'],list) else [entry['before']];old=hashlib.sha256(prior).hexdigest();entry.update(bytes=len(path.read_bytes()),sha256=hashlib.sha256(path.read_bytes()).hexdigest(),before=list(dict.fromkeys(allowed+[old])))
manpath.write_text(json.dumps(manifest,indent=2)+'\n')
css='.workbook-walkthrough{scroll-margin-top:5rem;margin-block:2rem}.workbook-walkthrough video{display:block;width:100%;height:auto;aspect-ratio:16/9;background:#0b2740;border-radius:16px;box-shadow:0 12px 30px #0b274016}.workbook-video-note{font-size:.95rem;color:#52666f;line-height:1.65}.workbook-video-transcript{margin-block:1.25rem;border:1px solid #dbe2df;border-radius:12px;padding:1rem}.workbook-video-transcript summary{cursor:pointer;font-weight:600}.workbook-video-transcript ol{padding-inline-start:1.5rem}.workbook-video-transcript li{margin-block:1rem}.workbook-video-transcript li p{margin-block:.35rem;line-height:1.7}@media(max-width:600px){.workbook-walkthrough video{border-radius:10px}.workbook-video-transcript{padding:.8rem}}\n'
(repo/'dist/workbook-video.css').write_text(css)
home=repo/'dist/home.js';prior=home.read_bytes();labels={l:t['watch'] for l,t in locales.items()};addon='\n/* Localized workbook walkthrough: follows the selected page language. */\n(() => {const actions=document.querySelector("#arabic .product-actions");if(!actions||actions.querySelector("[data-workbook-video]"))return;const lang=document.documentElement.lang||"en";const labels='+json.dumps(labels,ensure_ascii=False,separators=(',',':'))+';const link=document.createElement("a");link.className="text-link";link.dataset.workbookVideo="";link.href="product.html#workbook-walkthrough";link.textContent=labels[lang]||labels.en;actions.appendChild(link);})();\n';assert 'data-workbook-video' not in prior.decode();home.write_bytes(prior+addon.encode())
# The existing travel publisher owns home.js. Its exact previous public blob remains the baseline.
script=repo/'scripts/deploy-travel-kit.php';s=script.read_text();oldhash=hashlib.sha1(b'blob '+str(len(prior)).encode()+b'\0'+prior).hexdigest();s=s.replace("['public','dist/home.js','home.js','git-sha1:2a0ad467ec6b80cb63154de761548496b06a8918']",f"['public','dist/home.js','home.js','git-sha1:{oldhash}']");script.write_text(s)
print('Built 32 localized product videos and transcripts; existing purchase behavior retained.')
