<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(403);exit;}
ini_set('display_errors','0');ini_set('log_errors','0');umask(0077);
require_once __DIR__.'/blending4-preservation.php';
require_once __DIR__.'/comprehensive-meaning-preservation.php';
require_once __DIR__.'/blending3-preservation.php';
require_once __DIR__.'/blending2-preservation.php';
function b4Write(string $p,string $b,int $mode):void{$tmp=$p.'.b4-'.bin2hex(random_bytes(6));try{if(file_put_contents($tmp,$b)!==strlen($b)||!chmod($tmp,$mode)||!rename($tmp,$p))throw new RuntimeException('BLENDING4_WRITE_FAILED');}finally{if(is_file($tmp))unlink($tmp);}}
function b4Cipher(string $raw,string $key,string $path):string{$iv=random_bytes(12);$tag='';$c=openssl_encrypt($raw,'aes-256-gcm',$key,OPENSSL_RAW_DATA,$iv,$tag,'horizons-arabic-level1/'.$path,16);if($c===false)throw new RuntimeException('BLENDING4_ENCRYPT_FAILED');$result=$iv.$c.$tag;if(b4Plain($result,$key,$path)!==$raw)throw new RuntimeException('BLENDING4_ENCRYPT_CHECK_FAILED');return $result;}
function b4Plain(string $b,string $key,string $path):string{$p=strlen($b)>28?openssl_decrypt(substr($b,12,-16),'aes-256-gcm',$key,OPENSSL_RAW_DATA,substr($b,0,12),substr($b,-16),'horizons-arabic-level1/'.$path):false;if($p===false)throw new RuntimeException('BLENDING4_DECRYPT_FAILED');return $p;}
$lock=null;$written=[];$newFiles=[];$originals=[];$private='';$created=false;$restoreFailed=false;$failed=false;
try{
 if(count($argv)<2||count($argv)>4||(isset($argv[3])&&$argv[3]!=='--publish'))throw new RuntimeException('BLENDING4_ARGUMENTS_INVALID');
 $input=rtrim($argv[1],'/');$web=realpath($input);$repo=realpath(dirname(__DIR__));if(!$web||$web!==$input||$web==='/'||is_link($input)||str_starts_with($repo.'/',$web.'/'))throw new RuntimeException('BLENDING4_ROOT_INVALID');$home=dirname($web);
 $release=hznB4Release($repo);$current=hznB4State($web);if($current){hznCMState($web);hznB3State($web);hznBlending2SupersedingState($web);echo "CURRENT: Section 05; 159 recordings, 27 lessons, 32 languages.\n";exit;}
 $publish=in_array('--publish',$argv,true);$bundle=$argv[2]??'';if(!$bundle||$bundle==='--publish'||is_link($bundle)||!($bundleReal=realpath($bundle))||!str_starts_with($bundleReal,$home.'/')||str_starts_with($bundleReal.'/',$web.'/')||$bundleReal===$home)throw new RuntimeException('BLENDING4_PRIVATE_BUNDLE_REQUIRED');
 $previous=hznCMState($web);if(!$previous||!hznB3State($web)||!hznBlending2SupersedingState($web))throw new RuntimeException('BLENDING4_APPROVED_BASELINE_REQUIRED');
 foreach(HZN_B4_SHARED as $p){$raw=hznB4Read(hznB4Path($web,$p));if(!hash_equals($previous['hashes'][$p],hash('sha256',$raw)))throw new RuntimeException('BLENDING4_BASELINE_CHANGED');$originals[$p]=['bytes'=>$raw,'mode'=>fileperms(hznB4Path($web,$p))&0777];}
 $manifest=json_decode($originals['learn/asset-manifest.json']['bytes'],true,32,JSON_THROW_ON_ERROR);if(isset($manifest['blending4_release'])||isset($manifest['groups']['blending4'])||($manifest['meaning_languages']??[])!==$release['languages'])throw new RuntimeException('BLENDING4_CONFLICTING_RELEASE');
 $pointer=require hznB4Path($web,'activation/config-path.php');if(!is_string($pointer)||is_link($pointer)||!($cp=realpath($pointer))||!str_starts_with($cp,$home.'/')||str_starts_with($cp,$web.'/'))throw new RuntimeException('BLENDING4_PRIVATE_CONFIG_REQUIRED');ob_start();try{$config=require $cp;}finally{ob_end_clean();}
 $vp=$config['vault_path']??'';if(!is_string($vp)||is_link($vp)||!($vr=realpath($vp))||!str_starts_with($vr,$home.'/')||str_starts_with($vr,$web.'/'))throw new RuntimeException('BLENDING4_PRIVATE_VAULT_REQUIRED');$vault=json_decode(hznB4Read($vr,65536),true,8,JSON_THROW_ON_ERROR);$key=base64_decode($vault['content_key']??'',true);if(($vault['product']??'')!=='horizons-arabic-level1'||!is_string($key)||strlen($key)!==32)throw new RuntimeException('BLENDING4_VAULT_INVALID');
 $plain=gzdecode(b4Plain($originals['learn/content/1.4.1/workbook.js.hzn']['bytes'],$key,'workbook.js'),33554432);if($plain===false||strlen($plain)!==$manifest['files']['workbook.js']['decoded_bytes']||!hash_equals($previous['plain_after_sha256'],hash('sha256',$plain)))throw new RuntimeException('BLENDING4_PLAIN_BASELINE_CHANGED');
 $source=hznB4Read(hznB4Path($repo,'src/workbook-web/blending4-extension.js'));$tail="\ninit();\n\n})();";$extension="\n".rtrim($source,"\r\n")."\n";
 if(substr_count($plain,$tail)!==1||str_contains($plain,'/*BLENDING4_EXTENSION_BEGIN*/')||substr_count($source,'/*BLENDING4_EXTENSION_BEGIN*/')!==1||substr_count($source,'/*BLENDING4_EXTENSION_END*/')!==1)throw new RuntimeException('BLENDING4_HOOK_INVALID');$updated=str_replace($tail,$extension.$tail,$plain);if(strlen($updated)>33554432||str_replace($extension.$tail,$tail,$updated)!==$plain)throw new RuntimeException('BLENDING4_PRIOR_SOURCE_CHANGED');
 $plainBefore=hash('sha256',$plain);$plainAfter=hash('sha256',$updated);$payload=[];$app=b4Cipher(gzencode($updated,9),$key,'workbook.js');$payload['learn/content/1.4.1/workbook.js.hzn']=$app;$manifest['files']['workbook.js']['sha256']=hash('sha256',$app);$manifest['files']['workbook.js']['bytes']=strlen($app);$manifest['files']['workbook.js']['decoded_bytes']=strlen($updated);
 foreach($release['assets'] as $p=>$spec){$raw=hznB4Read(hznB4Path($bundleReal,$p),16000000);if(strlen($raw)!==$spec['bytes']||!hash_equals($spec['sha256'],hash('sha256',$raw))||isset($manifest['files'][$p]))throw new RuntimeException('BLENDING4_BUNDLE_CHANGED');$sourceBytes=str_ends_with($p,'.json')?gzencode($raw,9):$raw;$cipher=b4Cipher($sourceBytes,$key,$p);$url='content/1.4.1/'.$p.'.hzn';if(file_exists(hznB4Path($web,'learn/'.$url)))throw new RuntimeException('BLENDING4_TARGET_EXISTS');$payload['learn/'.$url]=$cipher;$entry=['url'=>$url,'sha256'=>hash('sha256',$cipher),'bytes'=>strlen($cipher),'mime'=>$spec['mime']];if(str_ends_with($p,'.json')){$entry['encoding']='gzip';$entry['decoded_bytes']=strlen($raw);}$manifest['files'][$p]=$entry;$manifest['groups']['all'][]=$p;}
 $manifest['groups']['blending4']=array_merge(['workbook.js'],array_keys($release['assets']));$manifest['blending4_release']=HZN_B4_RELEASE;$manifest['blending4_word_count']=159;$manifest['blending4_approved_clips']=159;$manifest['blending4_lesson_count']=27;$manifest['blending4_languages']=$release['languages'];$payload['learn/asset-manifest.json']=hznB4Json($manifest)."\n";$payload['learn/sw.js']=hznB4Worker($originals['learn/sw.js']['bytes']);unset($key,$vault,$config,$plain,$updated,$cipher,$raw,$sourceBytes);
 if(!$publish){echo "READY: Section 05 private content verified; 160 new encrypted assets plus existing application; no files published.\n";exit;}
 $lockPath=hznB4Path($home,'.horizons-blending4.lock');$lock=fopen($lockPath,'c');if(!$lock||!flock($lock,LOCK_EX|LOCK_NB))throw new RuntimeException('BLENDING4_DEPLOY_BUSY');chmod($lockPath,0600);
 $private=hznB4Path($home,'.horizons-blending4');if(file_exists($private)||!mkdir($private,0700))throw new RuntimeException('BLENDING4_PRIVATE_STATE_CONFLICT');$created=true;
 $before=[];foreach(HZN_B4_SHARED as $p){$backup=hznB4Path($private,'baseline/'.$p);if(!is_dir(dirname($backup))&&!mkdir(dirname($backup),0700,true))throw new RuntimeException('BLENDING4_BACKUP_FAILED');b4Write($backup,$originals[$p]['bytes'],0600);$before[$p]=hash('sha256',$originals[$p]['bytes']);}
 $priorReceipt=hznB4Read(hznB4Path($home,'.horizons-comprehensive-meaning/receipt.json'),65536);foreach(HZN_B4_SHARED as $p)if(hznB4Read(hznB4Path($web,$p))!==$originals[$p]['bytes'])throw new RuntimeException('BLENDING4_CONCURRENT_CHANGE');
 // Write encrypted new assets first, then the player and manifest, worker last.
 $order=array_merge(array_map(fn($p)=>'learn/content/1.4.1/'.$p.'.hzn',array_keys($release['assets'])),['learn/content/1.4.1/workbook.js.hzn','learn/asset-manifest.json','learn/sw.js']);
 foreach($order as $p){$target=hznB4Path($web,$p);if(isset($originals[$p])&&hznB4Read($target)!==$originals[$p]['bytes'])throw new RuntimeException('BLENDING4_CONCURRENT_CHANGE');if(!is_dir(dirname($target))){if(!mkdir(dirname($target),0755,true))throw new RuntimeException('BLENDING4_PUBLIC_DIRECTORY_FAILED');$walk=dirname($target);while(str_starts_with($walk,$web.'/learn/content/1.4.1/course/')){chmod($walk,0755);$walk=dirname($walk);}}b4Write($target,$payload[$p],0644);$written[]=$p;if(!isset($originals[$p]))$newFiles[]=$p;}
 $hashes=[];foreach(array_merge(HZN_B4_SHARED,array_map(fn($p)=>'learn/content/1.4.1/'.$p.'.hzn',array_keys($release['assets']))) as $p)$hashes[$p]=hash('sha256',$payload[$p]);
 $receipt=['schema'=>1,'release'=>HZN_B4_RELEASE,'release_sha256'=>HZN_B4_RELEASE_SHA256,'sources'=>$release['sources'],'before_hashes'=>$before,'hashes'=>$hashes,'previous_receipt_sha256'=>hash('sha256',$priorReceipt),'plain_before_sha256'=>$plainBefore,'plain_after_sha256'=>$plainAfter];b4Write(hznB4Path($private,'receipt.json'),hznB4Json($receipt)."\n",0600);
 hznB4State($web);hznCMState($web);hznB3State($web);hznBlending2SupersedingState($web);
 echo "PUBLISHED: Section 05; 159 recordings, 27 lessons, 32 languages; predecessor receipts, content and learner data preserved.\n";
}catch(Throwable $error){$failed=true;foreach(array_reverse($written) as $p){try{if(isset($originals[$p]))b4Write(hznB4Path($web,$p),$originals[$p]['bytes'],$originals[$p]['mode']);elseif(is_file(hznB4Path($web,$p))&&!unlink(hznB4Path($web,$p)))throw new RuntimeException('RESTORE_FAILED');}catch(Throwable $ignored){$restoreFailed=true;}}
 if($created&&!$restoreFailed){$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($private,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $f){if($f->isDir())rmdir($f->getPathname());else unlink($f->getPathname());}rmdir($private);}
 $code=$error instanceof RuntimeException&&preg_match('/^[A-Z0-9_]+$/D',$error->getMessage())?$error->getMessage():'BLENDING4_DEPLOY_FAILED';fwrite(STDERR,'STOP: '.$code.($restoreFailed?'; RESTORE_REQUIRES_ATTENTION':'; published changes rolled back')."\n");
}finally{if(is_resource($lock)){flock($lock,LOCK_UN);fclose($lock);}}
exit($failed?1:0);
