#!/usr/bin/env python3
import json
from pathlib import Path
# Independently translated UI text; currency and country names use browser Intl data.
KEYS='display_title display_currency display_hint display_estimate display_details display_note display_unavailable'.split()
ROWS={
'en':['See the price in your currency','Display currency','Choose a country to select its currency automatically, or choose another currency.','Estimated total','Daily reference · {date}.','The display currency does not change the payment currency. Your card issuer determines its exchange rate, fees and the final debit in your card account currency.','A current conversion is unavailable for this currency. The original price is unchanged; please choose another currency.'],
'ar':['شاهد السعر بعملتك','عملة عرض السعر','اختر البلد لتظهر عملته تلقائيًا، ويمكنك اختيار أي عملة أخرى.','الإجمالي التقديري','سعر مرجعي يومي · {date}.','عملة العرض لا تغيّر عملة الدفع. بنك بطاقتك يحدد سعر التحويل والرسوم والمبلغ النهائي الذي يُخصم بعملة حساب البطاقة.','التحويل الحالي غير متاح لهذه العملة. السعر الأصلي لم يتغير؛ يرجى اختيار عملة أخرى.'],
 'tr':['Fiyatı kendi para biriminizde görün','Görüntüleme para birimi','Para birimini otomatik seçmek için ülke seçin veya başka bir para birimi belirleyin.','Tahmini toplam','Günlük referans · {date}.','Görüntüleme para birimi ödeme para birimini değiştirmez. Kartınızı veren banka döviz kurunu, ücretleri ve kart hesabınızın para birimindeki son borç tutarını belirler.','Bu para birimi için güncel dönüşüm mevcut değil. Asıl fiyat değişmedi; lütfen başka bir para birimi seçin.'],
'fr':['Voir le prix dans votre devise','Devise d’affichage','Choisissez un pays pour sélectionner sa devise automatiquement, ou choisissez une autre devise.','Total estimé','Référence quotidienne · {date}.','La devise d’affichage ne change pas la devise de paiement. L’émetteur de votre carte détermine le taux de change, les frais et le débit final dans la devise de votre compte.','La conversion actuelle est indisponible pour cette devise. Le prix d’origine reste inchangé ; choisissez une autre devise.'],
'es':['Ver el precio en tu moneda','Moneda de visualización','Elige un país para seleccionar su moneda automáticamente, o elige otra moneda.','Total estimado','Referencia diaria · {date}.','La moneda mostrada no cambia la moneda de pago. El emisor de tu tarjeta determina el tipo de cambio, las comisiones y el cargo final en la moneda de tu cuenta.','No hay una conversión actual disponible para esta moneda. El precio original no cambia; elige otra moneda.'],
'de':['Preis in Ihrer Währung anzeigen','Anzeigewährung','Wählen Sie ein Land, um dessen Währung automatisch auszuwählen, oder wählen Sie eine andere Währung.','Geschätzter Gesamtbetrag','Täglicher Referenzkurs · {date}.','Die Anzeigewährung ändert die Zahlungswährung nicht. Ihr Kartenherausgeber bestimmt Wechselkurs, Gebühren und die endgültige Belastung in der Währung Ihres Kartenkontos.','Für diese Währung ist keine aktuelle Umrechnung verfügbar. Der ursprüngliche Preis bleibt unverändert; wählen Sie eine andere Währung.'],
'it':['Visualizza il prezzo nella tua valuta','Valuta di visualizzazione','Scegli un paese per selezionare automaticamente la sua valuta, oppure scegli un’altra valuta.','Totale stimato','Riferimento giornaliero · {date}.','La valuta visualizzata non cambia quella di pagamento. L’emittente della carta determina il cambio, le commissioni e l’addebito finale nella valuta del conto della carta.','La conversione attuale non è disponibile per questa valuta. Il prezzo originale non cambia; scegli un’altra valuta.'],
'pt':['Ver o preço na sua moeda','Moeda de apresentação','Escolha um país para selecionar automaticamente a sua moeda ou escolha outra moeda.','Total estimado','Referência diária · {date}.','A moeda apresentada não altera a moeda de pagamento. O emissor do cartão determina o câmbio, as comissões e o débito final na moeda da conta do cartão.','A conversão atual não está disponível para esta moeda. O preço original não muda; escolha outra moeda.'],
'nl':['Bekijk de prijs in uw valuta','Weergavevaluta','Kies een land om de valuta automatisch te selecteren, of kies een andere valuta.','Geschat totaal','Dagelijkse referentie · {date}.','De weergavevaluta verandert de betaalvaluta niet. Uw kaartuitgever bepaalt de wisselkoers, kosten en uiteindelijke afschrijving in de valuta van uw kaartrekening.','Er is geen actuele omrekening beschikbaar voor deze valuta. De oorspronkelijke prijs blijft gelijk; kies een andere valuta.'],
'ru':['Посмотреть цену в вашей валюте','Валюта отображения','Выберите страну для автоматического выбора её валюты или выберите другую валюту.','Примерная сумма','Дневной справочный курс · {date}.','Валюта отображения не меняет валюту платежа. Банк, выпустивший карту, определяет курс, комиссии и окончательное списание в валюте счёта карты.','Актуальный пересчёт для этой валюты недоступен. Исходная цена не изменилась; выберите другую валюту.'],
'uk':['Переглянути ціну у вашій валюті','Валюта відображення','Виберіть країну, щоб автоматично вибрати її валюту, або виберіть іншу валюту.','Орієнтовна сума','Щоденний довідковий курс · {date}.','Валюта відображення не змінює валюту платежу. Банк, що видав картку, визначає курс, комісії та остаточне списання у валюті рахунку картки.','Актуальний перерахунок для цієї валюти недоступний. Початкова ціна не змінилася; виберіть іншу валюту.'],
'pl':['Zobacz cenę w swojej walucie','Waluta wyświetlania','Wybierz kraj, aby automatycznie wybrać jego walutę, lub wybierz inną walutę.','Szacowana suma','Dzienny kurs referencyjny · {date}.','Waluta wyświetlania nie zmienia waluty płatności. Wydawca karty ustala kurs, opłaty i ostateczne obciążenie w walucie rachunku karty.','Aktualne przeliczenie dla tej waluty jest niedostępne. Cena pierwotna nie uległa zmianie; wybierz inną walutę.'],
'cs':['Zobrazit cenu ve vaší měně','Měna zobrazení','Vyberte zemi pro automatickou volbu její měny, nebo zvolte jinou měnu.','Odhadovaný součet','Denní referenční kurz · {date}.','Měna zobrazení nemění měnu platby. Vydavatel karty určuje kurz, poplatky a konečnou částku strženou v měně karetního účtu.','Aktuální přepočet pro tuto měnu není dostupný. Původní cena se nemění; vyberte jinou měnu.'],
'ro':['Vezi prețul în moneda ta','Moneda afișată','Alege o țară pentru selectarea automată a monedei sale sau alege altă monedă.','Total estimat','Curs de referință zilnic · {date}.','Moneda afișată nu schimbă moneda plății. Emitentul cardului stabilește cursul, comisioanele și debitarea finală în moneda contului cardului.','Conversia actuală nu este disponibilă pentru această monedă. Prețul inițial nu s-a schimbat; alege altă monedă.'],
'hu':['Ár megtekintése saját pénznemben','Megjelenítési pénznem','Válasszon országot a pénznem automatikus kiválasztásához, vagy válasszon másik pénznemet.','Becsült végösszeg','Napi referenciaárfolyam · {date}.','A megjelenítési pénznem nem módosítja a fizetés pénznemét. A kártyakibocsátó határozza meg az árfolyamot, a díjakat és a kártyaszámla pénznemében terhelt végösszeget.','Ehhez a pénznemhez nem érhető el aktuális átváltás. Az eredeti ár változatlan; válasszon másik pénznemet.'],
'el':['Δείτε την τιμή στο νόμισμά σας','Νόμισμα εμφάνισης','Επιλέξτε χώρα για αυτόματη επιλογή του νομίσματός της ή επιλέξτε άλλο νόμισμα.','Εκτιμώμενο σύνολο','Ημερήσια τιμή αναφοράς · {date}.','Το νόμισμα εμφάνισης δεν αλλάζει το νόμισμα πληρωμής. Ο εκδότης της κάρτας καθορίζει την ισοτιμία, τις χρεώσεις και την τελική χρέωση στο νόμισμα του λογαριασμού της κάρτας.','Δεν διατίθεται τρέχουσα μετατροπή για αυτό το νόμισμα. Η αρχική τιμή παραμένει ίδια· επιλέξτε άλλο νόμισμα.'],
'sv':['Visa priset i din valuta','Visningsvaluta','Välj ett land för att automatiskt välja dess valuta, eller välj en annan valuta.','Uppskattat totalbelopp','Daglig referenskurs · {date}.','Visningsvalutan ändrar inte betalningsvalutan. Din kortutgivare bestämmer växelkurs, avgifter och slutlig debitering i kortkontots valuta.','Aktuell omräkning är inte tillgänglig för denna valuta. Ursprungligt pris är oförändrat; välj en annan valuta.'],
'da':['Se prisen i din valuta','Visningsvaluta','Vælg et land for automatisk at vælge landets valuta, eller vælg en anden valuta.','Anslået total','Daglig referencekurs · {date}.','Visningsvalutaen ændrer ikke betalingsvalutaen. Din kortudsteder bestemmer kurs, gebyrer og den endelige debitering i kortkontoens valuta.','Aktuel omregning er ikke tilgængelig for denne valuta. Den oprindelige pris er uændret; vælg en anden valuta.'],
'no':['Se prisen i din valuta','Visningsvaluta','Velg et land for å velge landets valuta automatisk, eller velg en annen valuta.','Anslått totalbeløp','Daglig referansekurs · {date}.','Visningsvalutaen endrer ikke betalingsvalutaen. Kortutstederen bestemmer kurs, gebyrer og endelig belastning i kortkontoens valuta.','Gjeldende omregning er ikke tilgjengelig for denne valutaen. Den opprinnelige prisen er uendret; velg en annen valuta.'],
'fi':['Näytä hinta omassa valuutassasi','Näyttövaluutta','Valitse maa, jotta sen valuutta valitaan automaattisesti, tai valitse toinen valuutta.','Arvioitu yhteensä','Päivittäinen viitekurssi · {date}.','Näyttövaluutta ei muuta maksuvaluuttaa. Kortinmyöntäjä määrittää vaihtokurssin, kulut ja lopullisen veloituksen korttitilin valuutassa.','Ajantasainen muunnos ei ole saatavilla tälle valuutalle. Alkuperäinen hinta ei muutu; valitse toinen valuutta.'],
'bg':['Вижте цената във вашата валута','Валута за показване','Изберете държава за автоматичен избор на нейната валута или изберете друга валута.','Приблизителна обща сума','Дневен референтен курс · {date}.','Валутата за показване не променя валутата на плащане. Издателят на картата определя курса, таксите и крайното задължение във валутата на картовата сметка.','Текущото преобразуване за тази валута не е налично. Първоначалната цена не се променя; изберете друга валута.'],
'sr':['Погледајте цену у својој валути','Валута приказа','Изаберите државу за аутоматски избор њене валуте или изаберите другу валуту.','Процењени укупан износ','Дневни референтни курс · {date}.','Валута приказа не мења валуту плаћања. Издавалац картице одређује курс, накнаде и коначно задужење у валути рачуна картице.','Тренутна конверзија није доступна за ову валуту. Првобитна цена је непромењена; изаберите другу валуту.'],
'hr':['Pogledajte cijenu u svojoj valuti','Valuta prikaza','Odaberite državu za automatski odabir njezine valute ili odaberite drugu valutu.','Procijenjeni ukupni iznos','Dnevni referentni tečaj · {date}.','Valuta prikaza ne mijenja valutu plaćanja. Izdavatelj kartice određuje tečaj, naknade i konačno terećenje u valuti računa kartice.','Trenutačna konverzija nije dostupna za ovu valutu. Izvorna cijena ostaje ista; odaberite drugu valutu.'],
'he':['הצגת המחיר במטבע שלך','מטבע תצוגה','בחרו מדינה לבחירה אוטומטית של המטבע שלה, או בחרו מטבע אחר.','סכום משוער','שער ייחוס יומי · {date}.','מטבע התצוגה אינו משנה את מטבע התשלום. מנפיק הכרטיס קובע את שער ההמרה, העמלות והחיוב הסופי במטבע חשבון הכרטיס.','אין המרה עדכנית זמינה למטבע זה. המחיר המקורי לא השתנה; בחרו מטבע אחר.'],
'fa':['نمایش قیمت به ارز شما','ارز نمایش قیمت','کشور را برای انتخاب خودکار ارز آن انتخاب کنید، یا ارز دیگری برگزینید.','مجموع تقریبی','نرخ مرجع روزانه · {date}.','ارز نمایش قیمت، ارز پرداخت را تغییر نمی‌دهد. بانک صادرکننده کارت نرخ تبدیل، کارمزد و مبلغ نهایی کسرشده به ارز حساب کارت را تعیین می‌کند.','تبدیل به‌روز برای این ارز در دسترس نیست. قیمت اصلی تغییر نکرده است؛ ارز دیگری انتخاب کنید.'],
'ur':['قیمت اپنی کرنسی میں دیکھیں','قیمت دکھانے کی کرنسی','کرنسی خودکار منتخب کرنے کے لیے ملک چنیں، یا کوئی دوسری کرنسی منتخب کریں۔','تخمینی کل رقم','روزانہ کا حوالہ نرخ · {date}۔','دکھائی جانے والی کرنسی ادائیگی کی کرنسی کو تبدیل نہیں کرتی۔ کارڈ جاری کرنے والا بینک شرحِ تبادلہ، فیس اور کارڈ اکاؤنٹ کی کرنسی میں حتمی کٹوتی طے کرتا ہے۔','اس کرنسی کے لیے موجودہ تبدیلی دستیاب نہیں۔ اصل قیمت تبدیل نہیں ہوئی؛ دوسری کرنسی منتخب کریں۔'],
'hi':['कीमत अपनी मुद्रा में देखें','कीमत दिखाने की मुद्रा','देश चुनने पर उसकी मुद्रा अपने आप चुनी जाएगी, या कोई दूसरी मुद्रा चुनें।','अनुमानित कुल','दैनिक संदर्भ दर · {date}।','दिखाई गई मुद्रा से भुगतान की मुद्रा नहीं बदलती। आपका कार्ड जारीकर्ता विनिमय दर, शुल्क और कार्ड खाते की मुद्रा में अंतिम कटौती तय करता है।','इस मुद्रा के लिए मौजूदा रूपांतरण उपलब्ध नहीं है। मूल कीमत नहीं बदली है; कृपया दूसरी मुद्रा चुनें।'],
'bn':['আপনার মুদ্রায় দাম দেখুন','দাম দেখানোর মুদ্রা','দেশ বেছে নিলে তার মুদ্রা স্বয়ংক্রিয়ভাবে নির্বাচিত হবে, অথবা অন্য মুদ্রা বেছে নিন।','আনুমানিক মোট','দৈনিক রেফারেন্স হার · {date}।','দেখানো মুদ্রা পেমেন্টের মুদ্রা বদলায় না। আপনার কার্ড প্রদানকারী বিনিময় হার, ফি এবং কার্ড অ্যাকাউন্টের মুদ্রায় চূড়ান্ত কর্তনের পরিমাণ নির্ধারণ করে।','এই মুদ্রার জন্য বর্তমান রূপান্তর উপলব্ধ নেই। মূল দাম অপরিবর্তিত; অন্য মুদ্রা বেছে নিন।'],
'id':['Lihat harga dalam mata uang Anda','Mata uang tampilan','Pilih negara untuk memilih mata uangnya secara otomatis, atau pilih mata uang lain.','Perkiraan total','Kurs acuan harian · {date}.','Mata uang tampilan tidak mengubah mata uang pembayaran. Penerbit kartu menentukan kurs, biaya, dan debit akhir dalam mata uang rekening kartu Anda.','Konversi terkini tidak tersedia untuk mata uang ini. Harga asli tidak berubah; pilih mata uang lain.'],
'ms':['Lihat harga dalam mata wang anda','Mata wang paparan','Pilih negara untuk memilih mata wangnya secara automatik, atau pilih mata wang lain.','Anggaran jumlah','Kadar rujukan harian · {date}.','Mata wang paparan tidak mengubah mata wang pembayaran. Pengeluar kad menentukan kadar tukaran, fi dan debit akhir dalam mata wang akaun kad anda.','Penukaran semasa tidak tersedia untuk mata wang ini. Harga asal tidak berubah; pilih mata wang lain.'],
'zh':['以您的货币查看价格','显示货币','选择国家可自动选择其货币，也可以手动选择其他货币。','预计总额','每日参考汇率 · {date}。','显示货币不会改变付款货币。发卡银行决定兑换汇率、费用以及以银行卡账户货币扣除的最终金额。','此货币暂时没有可用的最新换算。原价未变，请选择其他货币。'],
'ja':['お使いの通貨で価格を表示','表示通貨','国を選択すると通貨が自動で選ばれます。別の通貨も選択できます。','概算合計','日次参考レート · {date}。','表示通貨を変更しても決済通貨は変わりません。カード発行会社が為替レート、手数料、カード口座の通貨での最終請求額を決定します。','この通貨の最新の換算は利用できません。元の価格は変わりません。別の通貨を選択してください。'],
}
assert len(ROWS)==32 and all(len(v)==len(KEYS) for v in ROWS.values())
if __name__=='__main__':
 (Path(__file__).resolve().parents[1]/'src/commerce/display-currency-locales.json').write_text(json.dumps({k:dict(zip(KEYS,v)) for k,v in ROWS.items()},ensure_ascii=False,indent=2)+'\n')
