// Authentic demo screens with localized instructions; never exposes paid lessons or learner data.
import fs from 'node:fs/promises';import fss from 'node:fs';import path from 'node:path';import http from 'node:http';import {spawnSync} from 'node:child_process';import {chromium} from 'playwright';
const [repo,work,only]=process.argv.slice(2);const locales=JSON.parse(await fs.readFile(path.join(repo,'scripts/workbook-video-locales.json'),'utf8'));const langs=only?only.split(','):Object.keys(locales);const root=path.join(work,'demo');
const mime={'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.mp3':'audio/mpeg'};
const server=http.createServer((req,res)=>{let f=path.join(root,new URL(req.url,'http://localhost').pathname);if(!f.startsWith(root+'/')){res.writeHead(403);res.end();return;}if(fss.existsSync(f)&&fss.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fss.existsSync(f)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',mime[path.extname(f)]||'application/octet-stream');fss.createReadStream(f).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const b=await chromium.launch({headless:true,executablePath:process.env.HZN_TRAVEL_CHROMIUM});const composite=await b.newPage({viewport:{width:1280,height:720},deviceScaleFactor:1});const reports=[];
async function compose(lang,step,bytes,name){const t=locales[lang],rtl=['ar','he','fa','ur'].includes(lang),data='data:image/jpeg;base64,'+bytes.toString('base64');
 await composite.setContent(`<!doctype html><html lang="${lang}" dir="${rtl?'rtl':'ltr'}"><meta charset="utf-8"><style>*{box-sizing:border-box}html,body{margin:0;width:1280px;height:720px;overflow:hidden}body{background:#0b2740;color:#fff;font-family:Arial,'Noto Sans','Noto Sans Arabic','Noto Sans Hebrew','Noto Sans Devanagari','Noto Sans Bengali',sans-serif}.bar{height:83px;padding:28px 36px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #ffffff25}.brand{letter-spacing:5px;font-weight:700;font-size:24px;color:#c9e5db}.counter{font-size:16px;letter-spacing:3px;color:#adc9d2}.frame{display:grid;grid-template-columns:305px 1fr;gap:28px;padding:30px 36px;height:586px;align-items:center}.copy{min-width:0}.mini{font-size:14px;line-height:1.6;color:#b6d1d5;margin:0 0 22px}h1{font-size:35px;line-height:1.3;margin:0 0 22px;color:#f8e9c7;max-height:175px}p.caption{font-size:24px;line-height:1.65;margin:0;max-height:295px}.screen{min-width:0;height:518px;display:flex;align-items:center;justify-content:center;direction:ltr}.screen img{width:100%;max-height:100%;object-fit:contain;border-radius:12px;box-shadow:0 20px 50px #0005}.footer{position:absolute;bottom:0;left:36px;right:36px;height:51px;display:flex;align-items:center;justify-content:space-between;color:#a7c4ce;font-size:14px;border-top:1px solid #ffffff25}.pill{border:1px solid #ffffff35;border-radius:30px;padding:6px 16px;color:#e1eee8}</style><body><div class="bar"><span class="brand" dir="ltr">HORIZONS</span><span class="counter" dir="ltr">${String(step+1).padStart(2,'0')} / 07 · ${lang.toUpperCase()}</span></div><div class="frame"><div class="copy"><p class="mini">${escape(t.title)}</p><h1>${escape(t.steps[step])}</h1><p class="caption">${escape(t.captions[step])}</p></div><div class="screen"><img src="${data}" alt=""></div></div><div class="footer"><span class="pill">${escape(step===6?t.try:t.watch)}</span><span dir="ltr">horizons-tr.com</span></div></body></html>`);
 await composite.evaluate(()=>document.fonts.ready);await composite.evaluate(()=>{for(const e of document.querySelectorAll('h1,.caption')){const max=e.tagName==='H1'?175:295;while(e.scrollHeight>max&&parseFloat(getComputedStyle(e).fontSize)>18)e.style.fontSize=(parseFloat(getComputedStyle(e).fontSize)-1)+'px';}});
 const bad=await composite.evaluate(()=>[...document.querySelectorAll('h1,.caption,.copy')].some(e=>e.scrollWidth>e.clientWidth+2||e.scrollHeight>e.clientHeight+2));if(bad)throw Error('Localized caption overflow '+lang+' '+step);await composite.screenshot({path:name,type:'jpeg',quality:87});
}
async function shot(p){await p.evaluate(async()=>{await document.fonts.ready;const images=[...document.querySelectorAll('#activity img')];images.forEach(i=>i.loading='eager');await Promise.all(images.map(i=>i.decode().catch(()=>{})))});return p.locator('#activity').screenshot({type:'jpeg',quality:89});}
try{for(const lang of langs){
 const dir=path.join(work,'frames',lang);await fs.mkdir(dir,{recursive:true});const ctx=await b.newContext({viewport:{width:1366,height:1000},locale:lang,serviceWorkers:'block'});const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/try/?lang='+lang);await p.waitForFunction(()=>window.HORIZONS_BOOT?.ready,undefined,{timeout:30000});
 const observed=await p.evaluate(()=>({locale:document.documentElement.lang,dir:document.documentElement.dir,chapters:document.querySelectorAll('[data-letter]').length}));if(observed.locale!==lang||observed.chapters!==5)throw Error('Wrong demo '+lang);
 const intro=await fs.readFile(path.join(repo,'dist/assets/covers',lang,'arabic.png')); // Existing localized cover; supplied raster is used without retouching.
 await compose(lang,0,intro,path.join(dir,'0.jpg'));
 await p.locator('[data-audio="alphabet.baa"]').click();await p.waitForFunction(()=>!document.querySelector('[data-audio="alphabet.baa"]')?.classList.contains('playing'));await compose(lang,1,await shot(p),path.join(dir,'1.jpg'));
 await p.locator('#go-baa').click();await p.locator('[data-audio^="word."]').first().click();await p.waitForFunction(()=>!document.querySelector('[data-audio^="word."]')?.classList.contains('playing'));await compose(lang,2,await shot(p),path.join(dir,'2a.jpg'));
 await p.locator('[data-audio^="sentence."]').first().click();await p.waitForFunction(()=>!document.querySelector('[data-audio^="sentence."]')?.classList.contains('playing'));await compose(lang,2,await shot(p),path.join(dir,'2b.jpg'));
 await p.locator('[data-tab="quiz"]').click();await p.locator('[data-audio]').first().click();await p.waitForFunction(()=>!document.querySelector('[data-audio]')?.classList.contains('playing'));await compose(lang,3,await shot(p),path.join(dir,'3a.jpg'));await p.locator('[data-answer="0"]').click();if(!await p.locator('.choice.correct').count())throw Error('Quiz not completed '+lang);await compose(lang,3,await shot(p),path.join(dir,'3b.jpg'));
 await p.locator('[data-tab="stories"]').click();await compose(lang,4,await shot(p),path.join(dir,'4a.jpg'));await p.locator('[data-frame="1"]').click();await compose(lang,4,await shot(p),path.join(dir,'4b.jpg'));
 await p.locator('[data-tab="write"]').click();await compose(lang,5,await shot(p),path.join(dir,'5-0.jpg'));await p.locator('#play-pen').click();let animated=0;
 for(let j=1;j<=10;j++){await p.waitForTimeout(310);await compose(lang,5,await shot(p),path.join(dir,`5-${j}.jpg`));animated+=await p.locator('.pen-demo-stroke').evaluateAll(a=>a.filter(e=>e.style.opacity==='1').length);}
 if(!animated)throw Error('Pen demonstration did not animate '+lang);await p.locator('#clear').click();if(await p.locator('#confirm-dialog[open]').count())await p.locator('#confirm-yes').click();
 const points=await p.evaluate(()=>{const s=document.querySelector('.trace-guide'),c=document.querySelector('#ink'),path=s.querySelector('.pen-route');const r=c.getBoundingClientRect(),len=path.getTotalLength();return Array.from({length:25},(_,i)=>{const z=path.getPointAtLength(len*i/24);return {x:r.x+z.x/560*r.width,y:r.y+(z.y-70)/290*r.height}})});await p.mouse.move(points[0].x,points[0].y);await p.mouse.down();for(const z of points.slice(1))await p.mouse.move(z.x,z.y);await p.mouse.up();await compose(lang,5,await shot(p),path.join(dir,'5-manual.jpg'));await p.locator('#undo').click();await p.locator('#clear').click();if(await p.locator('#confirm-dialog[open]').count())await p.locator('#confirm-yes').click();
 await p.locator('#course-nav [data-course="alphabet"]').click();await compose(lang,6,await shot(p),path.join(dir,'6.jpg'));
 if(errors.length)throw Error('App errors '+lang+' '+errors.join(';'));reports.push({language:lang,...observed,quiz_correct:true,word_and_sentence_audio_played:true,story_frames:2,pen_animated:true,manual_trace_undo_clear:true,frames:21,page_errors:0});console.log('Captured authentic localized workbook steps: '+lang);await ctx.close();
 await fs.mkdir(path.join(work,'checks'),{recursive:true});await fs.writeFile(path.join(work,'checks',lang+'.json'),JSON.stringify(reports.at(-1),null,2));
} }finally{await b.close();server.close();}
