(() => {'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const types={individual:'فردي — متعلم واحد',family:'عائلي — خمسة متعلمين',institution:'مؤسسة — حتى 500 متعلم'},terms={monthly:'شهري',annual:'سنوي',lifetime:'مدى الحياة'},statuses={awaiting_payment:'بانتظار تأكيد الحوالة',paid:'بانتظار رقم الفاتورة',invoice_recorded:'جاهز لإصدار الاشتراك',fulfilled:'تم إصدار الاشتراك'};
const errors={LOGIN_REQUIRED:'انتهت الجلسة. ادخل مجددًا برمز من بريد الشركة.',REAUTH_REQUIRED:'لحماية حسابك، اطلب رمز دخول جديدًا ثم أكمل العملية.',LOGIN_INVALID:'الرمز غير صحيح أو انتهت صلاحيته. لديك خمس محاولات لكل رمز.',RATE_LIMITED:'وصلت إلى حد المحاولات. حاول لاحقًا.',MAIL_UNAVAILABLE:'تعذّر إرسال رمز الدخول. لم يحدث أي تغيير في اشتراكات العملاء.',EMAIL_MISMATCH:'البريدان غير متطابقين. راجع العنوان جيدًا.',AMOUNT_MISMATCH:'المبلغ أو العملة لا يطابقان الطلب. لم يتم تأكيد الدفع.',RECEIPT_REUSED:'مرجع الحوالة مستخدم بالفعل. راجع الطلب المرتبط به.',BANK_RECEIPT_REUSED:'مرجع الحوالة مرتبط بطلب آخر.',INVOICE_REQUIRED:'سجّل رقم الفاتورة الصادرة قبل إصدار الاشتراك.',INVOICE_CONFLICT:'يوجد رقم فاتورة مختلف محفوظ لهذا الطلب.',EMAIL_ALREADY_ASSIGNED:'البريد مرتبط بحساب آخر أو بعضوية عائلية/مؤسسية. لا يمكن إعادة تعيينه.',SUBSCRIPTION_ALREADY_ACTIVE:'هذا البريد يملك اشتراكًا دائمًا بالفعل.',FX_UNAVAILABLE:'تعذّر جلب سعر صرف حديث. اختر الدولار أو حاول لاحقًا.',FX_EXPIRED:'انتهى عرض الصرف. حدّث السعر ثم راجعه مجددًا.',WORKER_BUSY:'الخدمة تنفذ إجراءً آخر. أعد المحاولة بعد قليل.',INVALID_MARGIN:'اكتب هامشًا بين 0% و10%.',REQUEST_REUSED:'تغيرت بيانات الطلب أثناء الإرسال. راجعها ثم حاول مجددًا.'};
let csrf='',challenge='',catalog=null,quote=null,quoteTicket=0,requestId='',orderRows=[],page=0,customerPage=0,reviewMode=false,busy=false;
const money=(minor,currency)=>new Intl.NumberFormat('ar',{style:'currency',currency}).format(minor/100),date=n=>new Date(n*1000).toLocaleString('ar',{timeZone:'Europe/Istanbul'}),offerLabel=o=>`${types[o.account_type]} · ${terms[o.term]} · ${money(o.price_minor,'USD')}`;
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
async function api(action,data=null){const opt={credentials:'same-origin',cache:'no-store',redirect:'error',signal:AbortSignal.timeout(25000)};const parts=action.split('&');let url='api.php?action='+encodeURIComponent(parts.shift())+(parts.length?'&'+parts.join('&'):'');if(data!==null){opt.method='POST';opt.headers={'Content-Type':'application/json','X-CSRF-Token':csrf};opt.body=JSON.stringify({action,...data});url='api.php';}const r=await fetch(url,opt),v=await r.json();if(!r.ok||!v.ok){if(['LOGIN_REQUIRED','REAUTH_REQUIRED'].includes(v.error))showLogin();throw Error(v.error||'NETWORK');}if(v.csrf)csrf=v.csrf;return v;}
async function run(fn){if(busy)return;busy=true;document.body.setAttribute('aria-busy','true');try{await fn();}catch(e){status(errors[e.message]||'تعذّر إتمام العملية. حدّث القائمة للتحقق من الحالة قبل إعادة المحاولة.',true);}finally{busy=false;document.body.removeAttribute('aria-busy');}}
function showLogin(){$('dashboard').hidden=true;$('login').hidden=false;$('logout').hidden=true;$('login-form').hidden=true;challenge='';catalog=null;quote=null;quoteTicket++;orderRows=[];$('new-form').reset();$('login-form').reset();for(const id of ['detail','order-list','customer-list','audit'])$(id).replaceChildren();}
function confirmAction(title,body,yes='تأكيد'){return new Promise(resolve=>{$('confirm-title').textContent=title;$('confirm-body').innerHTML=body;$('confirm-yes').textContent=yes;const close=v=>{$('confirm-dialog').close();resolve(v);};$('confirm-yes').onclick=()=>close(true);$('confirm-no').onclick=()=>close(false);$('confirm-dialog').oncancel=e=>{e.preventDefault();close(false);};$('confirm-dialog').showModal();});}
function view(name){document.querySelectorAll('[data-view]').forEach(x=>x.hidden=x.id!==name);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('selected',x.dataset.tab===name));status('');}
async function boot(){const s=await api('state');if(!s.authenticated){showLogin();return;}catalog=s.catalog;$('login').hidden=true;$('dashboard').hidden=false;$('logout').hidden=false;$('settings-form').elements.margin.value=s.margin_bps/100;populateProducts();view('orders');await loadOrders();}
$('request-login').onclick=()=>run(async()=>{status('جارٍ إرسال الرمز إلى بريد الشركة…');const r=await api('request_login',{});challenge=r.challenge;$('login-form').hidden=false;$('login-form').elements.code.value='';$('login-form').elements.code.focus();status('أُرسل الرمز. افتح بريد info@horizons-tr.com ثم اكتبه هنا.');});
$('login-form').onsubmit=e=>{e.preventDefault();const code=e.currentTarget.elements.code.value.trim();run(async()=>{await api('verify_login',{challenge,code});$('login-form').reset();await boot();status('تم تسجيل الدخول.');});};
$('logout').onclick=()=>run(async()=>{await api('logout',{});showLogin();await api('state');status('تم تسجيل الخروج.');});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>run(async()=>{view(b.dataset.tab);if(b.dataset.tab==='orders')await loadOrders();if(b.dataset.tab==='customers')await loadCustomers();if(b.dataset.tab==='new')await refreshQuote();if(b.dataset.tab==='settings')await loadAudit();}));
$('new-top').onclick=()=>run(async()=>{view('new');await refreshQuote();});
const newForm=$('new-form');
const languages='ar tr en fr es de it pt nl ru uk pl cs ro hu el sv da no fi bg sr hr he fa ur hi bn id ms zh ja'.split(' '),names=new Intl.DisplayNames(['ar'],{type:'language'});newForm.elements.locale.replaceChildren();for(const lang of languages)newForm.elements.locale.add(new Option(names.of(lang),lang));
function populateProducts(){newForm.elements.product.replaceChildren();for(const p of Object.values(catalog.products))if(p.available&&p.fulfilment_adapter==='membership-v1')newForm.elements.product.add(new Option(p.name,p.id));populateOffers();}
function populateOffers(){newForm.elements.offer.replaceChildren();const p=catalog.products[newForm.elements.product.value];for(const o of p?.offers||[])newForm.elements.offer.add(new Option(offerLabel(o),o.id));}
function quoteHtml(q){return `<strong><bdi>${esc(money(q.amount_minor,q.currency))}</bdi></strong><p class="muted">السعر الأساسي: <bdi>${esc(money(q.base_minor,'USD'))}</bdi> · هامش التحويل: ${q.margin_bps/100}%<br>المصدر: <bdi>${esc(q.source)}</bdi> · تاريخ السعر: <bdi>${esc(q.rate_date)}</bdi><br>صالح حتى ${esc(date(q.expires_at))}</p>`;}
async function refreshQuote(){const ticket=++quoteTicket;quote=null;requestId='';$('create-order').disabled=true;$('new-quote').textContent='جارٍ جلب السعر…';try{const r=await api('quote',{product:newForm.elements.product.value,offer:newForm.elements.offer.value,currency:newForm.elements.currency.value});if(ticket!==quoteTicket)return;quote=r.quote;$('new-quote').innerHTML=quoteHtml(quote);$('create-order').disabled=false;}catch(e){if(ticket!==quoteTicket)return;$('new-quote').textContent=errors[e.message]||'تعذّر جلب السعر.';}}
newForm.addEventListener('input',()=>{requestId='';});newForm.elements.product.onchange=()=>{populateOffers();refreshQuote();};newForm.elements.offer.onchange=refreshQuote;newForm.elements.currency.onchange=refreshQuote;$('refresh-quote').onclick=refreshQuote;
newForm.elements.billing.onchange=()=>{const company=newForm.elements.billing.value==='company';$('company-fields').hidden=!company;for(const k of ['company_name','tax_id','tax_office']){newForm.elements[k].required=company;newForm.elements[k].disabled=!company;}};newForm.elements.billing.onchange();
newForm.onsubmit=e=>{e.preventDefault();if(!quote||quote.expires_at*1000<=Date.now()){refreshQuote();status('تم طلب سعر جديد. راجعه قبل الحفظ.',true);return;}const data=Object.fromEntries(new FormData(newForm));data.customer_confirmed=newForm.elements.customer_confirmed.checked;data.quote_token=quote.token;requestId||=crypto.randomUUID().replaceAll('-','');data.request_id=requestId;run(async()=>{if(data.email.trim().toLowerCase()!==data.email_confirm.trim().toLowerCase())throw Error('EMAIL_MISMATCH');if(!await confirmAction('راجع قبل حفظ الطلب',`<div class="summary"><div><small>العميل</small>${esc(data.name)}</div><div><small>البريد الثابت</small><bdi>${esc(data.email)}</bdi></div><div><small>الباقة</small>${esc(newForm.elements.offer.selectedOptions[0].textContent)}</div><div><small>المبلغ المطلوب</small><bdi>${esc(money(quote.amount_minor,quote.currency))}</bdi></div></div><p>الحفظ ينشئ طلبًا بانتظار الحوالة. لا يصدر تفعيلًا ولا يرسل رسالة للعميل.</p>`,'حفظ الطلب'))return;const r=await api('create_order',data);requestId='';showOrder(r.order);status('تم حفظ الطلب. الخطوة التالية: التحقق من وصول الحوالة.');});};
async function loadOrders(){const data=await api((reviewMode?'reviews':'orders')+'&page='+page);orderRows=data[reviewMode?'reviews':'orders'];$('page-label').textContent=`صفحة ${page+1}`;$('prev-page').disabled=page===0;$('next-page').disabled=!data.more;$('manual-orders').classList.toggle('selected',!reviewMode);$('review-orders').classList.toggle('selected',reviewMode);
    $('order-list').innerHTML=orderRows.length?orderRows.map(o=>{const d=o.data,b=d.buyer,q=d.quote||{amount_minor:d.offer.price_minor,currency:d.offer.currency};return `<article class="order-card"><div><h3>${esc(b.name||[b.first_name,b.last_name].filter(Boolean).join(' '))}</h3><p><bdi>${esc(b.email)}</bdi></p><p>${esc(types[d.offer.account_type])} · ${esc(terms[d.offer.term])}</p><span class="badge ${o.status==='fulfilled'?'done':'pending'}">${esc(reviewMode?'مراجعة فقط — غير مدفوع':statuses[o.status])}</span><bdi>${esc(money(q.amount_minor,q.currency))}</bdi><p class="reference" dir="ltr">${esc(o.id)}</p></div>${reviewMode?'<span class="muted">لا يمكن إصدار تفعيل من سجل مراجعة</span>':`<button data-open="${esc(o.id)}">${o.status==='fulfilled'?'عرض الاشتراك':'إكمال الخطوة التالية'}</button>`}</article>`;}).join(''):'<div class="empty">لا توجد طلبات هنا حتى الآن.</div>';
    document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>showOrder(orderRows.find(o=>o.id===b.dataset.open)));
}
// GET query values are constructed from bounded integers only.
async function loadCustomers(){const d=await api('customers&page='+customerPage);$('customers-prev').disabled=customerPage===0;$('customers-next').disabled=!d.more;$('customer-list').innerHTML=d.customers.length?d.customers.map(c=>`<article class="order-card"><div><h3><bdi>${esc(c.email)}</bdi></h3><p>${esc(types[c.account_type])} · ${esc(terms[c.plan])}</p><p>${c.expires_at?'ينتهي: '+esc(date(Number(c.expires_at))):'مدى الحياة'}</p></div><div><span class="badge">${Number(c.revoked)?'ملغى':c.expires_at&&Number(c.expires_at)*1000<Date.now()?'منتهي':'ساري'}</span><p class="muted">التفعيل: ${esc(({sent:'أُرسلت الرسالة',pending:'في قائمة الإرسال',cancelled:'ملغى'})[c.delivery_state]||'غير مسجل')}</p></div></article>`).join(''):'<div class="empty">لا توجد اشتراكات مسجلة.</div>';}
$('customers-prev').onclick=()=>run(async()=>{customerPage--;await loadCustomers();});$('customers-next').onclick=()=>run(async()=>{customerPage++;await loadCustomers();});
$('manual-orders').onclick=()=>run(async()=>{reviewMode=false;page=0;await loadOrders();});$('review-orders').onclick=()=>run(async()=>{reviewMode=true;page=0;await loadOrders();});$('refresh-orders').onclick=()=>run(loadOrders);$('prev-page').onclick=()=>run(async()=>{page--;await loadOrders();});$('next-page').onclick=()=>run(async()=>{page++;await loadOrders();});
function showOrder(o){view('detail');const d=o.data,b=d.buyer,q=d.quote,index=['awaiting_payment','paid','invoice_recorded','fulfilled'].indexOf(o.status);$('detail').innerHTML=`<div class="row"><div><span class="eyebrow">${esc(statuses[o.status])}</span><h2>${esc(b.name)}</h2></div><button id="back-orders" class="quiet">العودة إلى الطلبات</button></div><p class="reference" dir="ltr">${esc(o.id)}</p><div class="steps">${['بيانات العميل','تأكيد الحوالة','تسجيل الفاتورة','إصدار الاشتراك'].map((t,i)=>`<span class="${i<index+1?'done':''} ${i===index+1?'current':''}">${i+1}. ${t}</span>`).join('')}</div><div class="summary"><div><small>البريد الثابت</small><bdi>${esc(b.email)}</bdi></div><div><small>الباقة</small>${esc(types[d.offer.account_type])} · ${esc(terms[d.offer.term])}</div><div><small>المبلغ والعملة</small><bdi>${esc(money(q.amount_minor,q.currency))}</bdi></div><div><small>عنوان الفاتورة</small>${esc(b.country)} · ${esc(b.city)} · ${esc(b.address)}</div></div><div class="action-box" id="order-action"></div>`;
    $('back-orders').onclick=()=>run(async()=>{view('orders');reviewMode=false;page=0;await loadOrders();});
    if(o.status==='awaiting_payment'){$('order-action').innerHTML=`<h3>الخطوة التالية: تأكيد الحوالة</h3><p>افتح حساب البنك وتحقق من المبلغ المقيد فعلًا. صورة الإيصال المرسلة من العميل وحدها لا تكفي.</p><form id="payment-form"><div class="fields"><label>مرجع العملية في البنك<input name="bank_reference" pattern="[A-Za-z0-9_-]{6,120}" minlength="6" maxlength="120" dir="ltr" required></label><label>المبلغ المستلم (${esc(q.currency)})<input name="amount" inputmode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" dir="ltr" required placeholder="${(q.amount_minor/100).toFixed(2)}"></label></div><label class="check"><input name="verified" type="checkbox" required><span>تحققت من وصول هذا المبلغ إلى حساب الشركة بالعملة المكتوبة، ومن أنه يخص هذا الطلب.</span></label><button>مراجعة تأكيد الحوالة</button></form>`;$('payment-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,v=f.elements.amount.value.trim().split('.'),minor=Number(v[0])*100+Number((v[1]||'').padEnd(2,'0'));const input={id:o.id,bank_reference:f.elements.bank_reference.value.trim(),currency:q.currency,amount_minor:minor,verified:f.elements.verified.checked};run(async()=>{if(minor!==q.amount_minor)throw Error('AMOUNT_MISMATCH');if(!await confirmAction('هل وصلت الحوالة فعلًا؟',`<p><bdi>${esc(money(minor,q.currency))}</bdi> للعميل <bdi>${esc(b.email)}</bdi></p><p>مرجع البنك: <bdi>${esc(input.bank_reference)}</bdi></p>`,'نعم، سجّل وصول الحوالة'))return;const r=await api('record_payment',input);showOrder(r.order);status('تم تسجيل الحوالة. أصدر الفاتورة ثم سجّل رقمها.');});};}
    if(o.status==='paid'){$('order-action').innerHTML='<h3>الخطوة التالية: تسجيل الفاتورة</h3><p>أصدر الفاتورة من نظام الفواتير الذي تستخدمه، ثم أدخل رقمها هنا. هذه الخطوة تسجل فاتورة صادرة ولا تنشئ فاتورة ضريبية جديدة.</p><form id="invoice-form"><label>رقم الفاتورة الصادرة<input name="invoice" dir="ltr" pattern="[A-Za-z0-9-]{6,64}" required maxlength="64"></label><label class="check"><input name="issued" type="checkbox" required><span>أصدرت الفاتورة الصحيحة لهذا العميل والمبلغ.</span></label><button>حفظ رقم الفاتورة</button></form>';$('invoice-form').onsubmit=e=>{e.preventDefault();const input={id:o.id,invoice:e.currentTarget.elements.invoice.value.trim(),issued:e.currentTarget.elements.issued.checked};run(async()=>{if(!await confirmAction('تأكيد رقم الفاتورة',`<p><bdi>${esc(input.invoice)}</bdi></p>`,'حفظ الرقم'))return;const r=await api('record_invoice',input);showOrder(r.order);status('سُجلت الفاتورة. يمكنك الآن إصدار الاشتراك.');});};}
    if(o.status==='invoice_recorded'){$('order-action').innerHTML=`<h3>الخطوة الأخيرة: إصدار الاشتراك</h3><p>الفاتورة: <bdi>${esc(d.invoice)}</bdi>. سيُمنح العميل حقوق الباقة المحددة، ويُضاف كود التفعيل إلى قائمة الإرسال.</p><form id="fulfil-form"><label>أعد كتابة بريد العميل للتأكيد<input name="email" type="email" dir="ltr" required autocomplete="off"></label><label class="check"><input name="confirmed" type="checkbox" required><span>راجعت البريد والباقة، وأوافق على إصدار الاشتراك وإرسال رسالة التفعيل لهذا العميل.</span></label><button>إصدار الاشتراك وإرسال التفعيل</button></form>`;$('fulfil-form').onsubmit=e=>{e.preventDefault();const input={id:o.id,email:e.currentTarget.elements.email.value.trim(),confirmed:e.currentTarget.elements.confirmed.checked};run(async()=>{if(!await confirmAction('تأكيد إصدار الاشتراك',`<p>${esc(types[d.offer.account_type])} · ${esc(terms[d.offer.term])}</p><p><bdi>${esc(input.email)}</bdi></p><p>سيبدأ الاشتراك ويُرسل التفعيل إلى هذا البريد.</p>`,'إصدار الاشتراك'))return;const r=await api('fulfil',input);showOrder(r.order);status('تم إصدار الاشتراك. رسالة التفعيل في قائمة الإرسال التلقائية.');});};}
    if(o.status==='fulfilled'){$('order-action').innerHTML=`<h3>✓ الاشتراك جاهز</h3><p>تم إصدار الاشتراك. يمكن للعميل التفعيل ثم اختيار كلمة مروره. راقب حالة إرسال الرسالة في قسم العملاء.</p><p>الفاتورة: <bdi>${esc(d.invoice)}</bdi></p><button id="resend" class="quiet">إعادة إرسال التفعيل للبريد نفسه</button>`;$('resend').onclick=()=>run(async()=>{if(!await confirmAction('إعادة إرسال التفعيل',`<p>إلى <bdi>${esc(b.email)}</bdi> فقط. لن تُنشأ باقة إضافية.</p>`,'إعادة الإرسال'))return;await api('resend',{id:o.id});status('أضيفت الرسالة إلى قائمة الإرسال.');});}
}
$('settings-form').onsubmit=e=>{e.preventDefault();const margin=Math.round(Number(e.currentTarget.elements.margin.value)*100);run(async()=>{if(!await confirmAction('تغيير هامش التحويل',`<p>الهامش الجديد: ${esc(margin/100)}%. يطبق على عروض الصرف الجديدة فقط.</p>`,'حفظ الهامش'))return;await api('settings',{margin_bps:margin});status('حُفظ الهامش.');await loadAudit();});};
async function loadAudit(){const labels={owner_login:'دخول الإدارة',order_created:'إنشاء طلب',payment_verified:'تأكيد حوالة',invoice_recorded:'تسجيل فاتورة',membership_issued:'إصدار اشتراك',activation_requeued:'إعادة إرسال التفعيل',margin_changed:'تغيير هامش الصرف'};const d=await api('audit');$('audit').innerHTML=d.events.map(x=>`<div class="audit-row">${esc(labels[x.action]||x.action)} · <bdi>${esc(x.target)}</bdi> · ${esc(date(Number(x.created)))}</div>`).join('')||'<p>لا توجد إجراءات بعد.</p>';}
run(boot);
})();
